// Generated by tool/generate_feature_gateways.dart.
import 'package:synctv_app/features/admin/application/admin_gateway.dart';
import 'package:synctv_app/data/synctv_api/synctv_service.dart';
import 'package:synctv_app/contracts/synctv_api_types.dart';
import 'package:synctv_app/src/generated/proto/admin.pbenum.dart' as admin_enum;
import 'package:synctv_app/src/generated/proto/client.pbenum.dart'
    as client_enum;
import 'package:synctv_app/src/generated/proto/common.pbenum.dart'
    as common_enum;
import 'package:synctv_app/src/generated/proto/providers/common.pbenum.dart'
    as provider_common_enum;

final class SyncTvAdminGateway implements AdminGateway {
  const SyncTvAdminGateway();

  @override
  Future<void> adminAddAdmin(String userId) =>
      SyncTvService.adminAddAdmin(userId);

  @override
  Future<AdminProviderInstance> adminAddProviderInstance({
    required String name,
    required String endpoint,
    required List<String> providers,
    String comment = '',
    int timeoutSeconds = 30,
    bool tls = true,
    bool insecureTls = false,
    String? jwtSecret,
    String? customCa,
  }) => SyncTvService.adminAddProviderInstance(
    name: name,
    endpoint: endpoint,
    providers: providers,
    comment: comment,
    timeoutSeconds: timeoutSeconds,
    tls: tls,
    insecureTls: insecureTls,
    jwtSecret: jwtSecret,
    customCa: customCa,
  );

  @override
  Future<void> adminAddRoomMember(
    String roomId,
    String userId, {
    common_enum.RoomMemberRole role =
        common_enum.RoomMemberRole.ROOM_MEMBER_ROLE_ADMIN,
    bool notify = true,
  }) => SyncTvService.adminAddRoomMember(
    roomId,
    userId,
    role: role,
    notify: notify,
  );

  @override
  Future<void> adminAddUser(
    String username,
    String password,
    common_enum.UserRole role, {
    String email = '',
    common_enum.UserStatus status = common_enum.UserStatus.USER_STATUS_ACTIVE,
  }) => SyncTvService.adminAddUser(
    username,
    password,
    role,
    email: email,
    status: status,
  );

  @override
  Future<void> adminApproveReview(AdminReviewKind kind, String requestId) =>
      SyncTvService.adminApproveReview(kind, requestId);

  @override
  Future<void> adminBanRoom(String roomId, bool ban, {String reason = ''}) =>
      SyncTvService.adminBanRoom(roomId, ban, reason: reason);

  @override
  Future<void> adminBanUser(String userId, bool ban, {String reason = ''}) =>
      SyncTvService.adminBanUser(userId, ban, reason: reason);

  @override
  Future<AdminBatchOperationResult> adminBatchBanRooms(
    List<String> roomIds, {
    String reason = '',
  }) => SyncTvService.adminBatchBanRooms(roomIds, reason: reason);

  @override
  Future<AdminBatchOperationResult> adminBatchBanUsers(
    List<String> userIds, {
    String reason = '',
  }) => SyncTvService.adminBatchBanUsers(userIds, reason: reason);

  @override
  Future<AdminBatchOperationResult> adminBatchDeleteRooms(
    List<String> roomIds,
  ) => SyncTvService.adminBatchDeleteRooms(roomIds);

  @override
  Future<AdminBatchOperationResult> adminBatchDeleteUsers(
    List<String> userIds,
  ) => SyncTvService.adminBatchDeleteUsers(userIds);

  @override
  Future<void> adminDeleteProviderInstance(String name) =>
      SyncTvService.adminDeleteProviderInstance(name);

  @override
  Future<void> adminDeleteRoom(String roomId) =>
      SyncTvService.adminDeleteRoom(roomId);

  @override
  Future<void> adminDeleteRoomCategory(String categoryId) =>
      SyncTvService.adminDeleteRoomCategory(categoryId);

  @override
  Future<void> adminDeleteRoomLabel(String labelId) =>
      SyncTvService.adminDeleteRoomLabel(labelId);

  @override
  Future<void> adminDeleteUser(String userId) =>
      SyncTvService.adminDeleteUser(userId);

  @override
  Future<AdminSliceCacheOperationResult> adminEvictExpiredSliceCache({
    String nodeId = '',
    bool allNodes = false,
  }) => SyncTvService.adminEvictExpiredSliceCache(
    nodeId: nodeId,
    allNodes: allNodes,
  );

  @override
  Future<SyncTvRoom> adminGetRoom(String roomId) =>
      SyncTvService.adminGetRoom(roomId);

  @override
  Future<SyncTvRoomSettings> adminGetRoomSettings(
    String roomId, {
    bool refresh = false,
  }) => SyncTvService.adminGetRoomSettings(roomId, refresh: refresh);

  @override
  Future<AdminServiceState> adminGetServiceState() =>
      SyncTvService.adminGetServiceState();

  @override
  Future<AdminSliceCacheStats> adminGetSliceCacheStats({
    String nodeId = '',
    bool allNodes = false,
  }) =>
      SyncTvService.adminGetSliceCacheStats(nodeId: nodeId, allNodes: allNodes);

  @override
  Future<SyncTvUser> adminGetUser(String userId) =>
      SyncTvService.adminGetUser(userId);

  @override
  Future<AccountPreferences> adminGetUserPreferences(String userId) =>
      SyncTvService.adminGetUserPreferences(userId);

  @override
  Future<void> adminKickRoomMember(
    String roomId,
    String userId, {
    int kickCooldownSeconds = 60,
  }) => SyncTvService.adminKickRoomMember(
    roomId,
    userId,
    kickCooldownSeconds: kickCooldownSeconds,
  );

  @override
  Future<void> adminKickStream(AdminActiveStream stream) =>
      SyncTvService.adminKickStream(stream);

  @override
  Future<AdminActiveStreamsPage> adminListActiveStreamsPage({
    int page = 1,
    int pageSize = 50,
    String roomId = '',
    String userId = '',
    String nodeId = '',
    String search = '',
    admin_enum.ActiveStreamListSortBy sortBy =
        admin_enum.ActiveStreamListSortBy.ACTIVE_STREAM_LIST_SORT_BY_STARTED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  }) => SyncTvService.adminListActiveStreamsPage(
    page: page,
    pageSize: pageSize,
    roomId: roomId,
    userId: userId,
    nodeId: nodeId,
    search: search,
    sortBy: sortBy,
    sortDirection: sortDirection,
  );

  @override
  Future<AdminsPage> adminListAdminsPage({
    int page = 1,
    int pageSize = 20,
    String search = '',
    admin_enum.UserListSortBy sortBy =
        admin_enum.UserListSortBy.USER_LIST_SORT_BY_CREATED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  }) => SyncTvService.adminListAdminsPage(
    page: page,
    pageSize: pageSize,
    search: search,
    sortBy: sortBy,
    sortDirection: sortDirection,
  );

  @override
  Future<AdminBanRecordsPage> adminListBanRecordsPage({
    int page = 1,
    int pageSize = 50,
    admin_enum.BanTargetType targetType =
        admin_enum.BanTargetType.BAN_TARGET_TYPE_UNSPECIFIED,
    bool? active,
    String userId = '',
    String roomId = '',
  }) => SyncTvService.adminListBanRecordsPage(
    page: page,
    pageSize: pageSize,
    targetType: targetType,
    active: active,
    userId: userId,
    roomId: roomId,
  );

  @override
  Future<AdminProviderInstancesPage> adminListProviderInstancesPage({
    int page = 1,
    int pageSize = 50,
    String providerType = '',
    String search = '',
    bool? enabled,
    bool? tls,
    provider_common_enum.ProviderInstanceListSortBy sortBy =
        provider_common_enum
            .ProviderInstanceListSortBy
            .PROVIDER_INSTANCE_LIST_SORT_BY_NAME,
    provider_common_enum.SortDirection sortDirection =
        provider_common_enum.SortDirection.SORT_DIRECTION_ASC,
  }) => SyncTvService.adminListProviderInstancesPage(
    page: page,
    pageSize: pageSize,
    providerType: providerType,
    search: search,
    enabled: enabled,
    tls: tls,
    sortBy: sortBy,
    sortDirection: sortDirection,
  );

  @override
  Future<AdminReviewsPage> adminListReviewsPage({
    required AdminReviewKind kind,
    int page = 1,
    int pageSize = 50,
    common_enum.ReviewStatus status =
        common_enum.ReviewStatus.REVIEW_STATUS_PENDING,
    String search = '',
    String requestedBy = '',
    String roomId = '',
    String userId = '',
  }) => SyncTvService.adminListReviewsPage(
    kind: kind,
    page: page,
    pageSize: pageSize,
    status: status,
    search: search,
    requestedBy: requestedBy,
    roomId: roomId,
    userId: userId,
  );

  @override
  Future<List<RoomCategoryInfo>> adminListRoomCategories({
    bool includeDisabled = false,
    bool refresh = false,
  }) => SyncTvService.adminListRoomCategories(
    includeDisabled: includeDisabled,
    refresh: refresh,
  );

  @override
  Future<List<RoomLabelInfo>> adminListRoomLabels({
    bool includeDisabled = false,
    String categoryId = '',
    bool refresh = false,
  }) => SyncTvService.adminListRoomLabels(
    includeDisabled: includeDisabled,
    categoryId: categoryId,
    refresh: refresh,
  );

  @override
  Future<AdminRoomMembersPage> adminListRoomMembersPage(
    String roomId, {
    int page = 1,
    int pageSize = 100,
    String search = '',
    common_enum.RoomMemberRole? role,
    admin_enum.RoomMemberListSortBy sortBy =
        admin_enum.RoomMemberListSortBy.ROOM_MEMBER_LIST_SORT_BY_JOINED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  }) => SyncTvService.adminListRoomMembersPage(
    roomId,
    page: page,
    pageSize: pageSize,
    search: search,
    role: role,
    sortBy: sortBy,
    sortDirection: sortDirection,
  );

  @override
  Future<AdminRoomsPage> adminListRoomsPage({
    int page = 1,
    int pageSize = 20,
    String? search,
    String categoryId = '',
    List<String> labelIds = const [],
    common_enum.RoomStatus status =
        common_enum.RoomStatus.ROOM_STATUS_UNSPECIFIED,
    bool? isBanned,
    admin_enum.RoomListSortBy sortBy =
        admin_enum.RoomListSortBy.ROOM_LIST_SORT_BY_CREATED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  }) => SyncTvService.adminListRoomsPage(
    page: page,
    pageSize: pageSize,
    search: search,
    categoryId: categoryId,
    labelIds: labelIds,
    status: status,
    isBanned: isBanned,
    sortBy: sortBy,
    sortDirection: sortDirection,
  );

  @override
  Future<AdminRoomsPage> adminListUserRoomsPage(
    String userId, {
    int page = 1,
    int pageSize = 20,
    String search = '',
    common_enum.RoomStatus status =
        common_enum.RoomStatus.ROOM_STATUS_UNSPECIFIED,
    bool? isBanned,
    admin_enum.RoomListSortBy sortBy =
        admin_enum.RoomListSortBy.ROOM_LIST_SORT_BY_CREATED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  }) => SyncTvService.adminListUserRoomsPage(
    userId,
    page: page,
    pageSize: pageSize,
    search: search,
    status: status,
    isBanned: isBanned,
    sortBy: sortBy,
    sortDirection: sortDirection,
  );

  @override
  Future<AdminUsersPage> adminListUsersPage({
    int page = 1,
    int pageSize = 20,
    String? search,
    common_enum.UserStatus status =
        common_enum.UserStatus.USER_STATUS_UNSPECIFIED,
    common_enum.UserRole role = common_enum.UserRole.USER_ROLE_UNSPECIFIED,
    bool? isBanned,
    admin_enum.UserListSortBy sortBy =
        admin_enum.UserListSortBy.USER_LIST_SORT_BY_CREATED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  }) => SyncTvService.adminListUsersPage(
    page: page,
    pageSize: pageSize,
    search: search,
    status: status,
    role: role,
    isBanned: isBanned,
    sortBy: sortBy,
    sortDirection: sortDirection,
  );

  @override
  Future<void> adminModerateRoomChatUser(
    String roomId,
    String userId, {
    required bool deleteAllMessages,
    required bool deleteAllReactions,
    required bool ban,
    String messageId = '',
    String reason = '',
  }) => SyncTvService.adminModerateRoomChatUser(
    roomId,
    userId,
    deleteAllMessages: deleteAllMessages,
    deleteAllReactions: deleteAllReactions,
    ban: ban,
    messageId: messageId,
    reason: reason,
  );

  @override
  Future<AdminSliceCacheOperationResult> adminPurgeSliceCache({
    String nodeId = '',
    bool allNodes = false,
  }) => SyncTvService.adminPurgeSliceCache(nodeId: nodeId, allNodes: allNodes);

  @override
  Future<void> adminReconnectProviderInstance(String name) =>
      SyncTvService.adminReconnectProviderInstance(name);

  @override
  Future<void> adminRejectReview(
    AdminReviewKind kind,
    String requestId, {
    String reason = '',
  }) => SyncTvService.adminRejectReview(kind, requestId, reason: reason);

  @override
  Future<void> adminRemoveAdmin(String userId) =>
      SyncTvService.adminRemoveAdmin(userId);

  @override
  Future<void> adminResetRoomSettings(String roomId) =>
      SyncTvService.adminResetRoomSettings(roomId);

  @override
  Future<String> adminSendTestEmail(String to) =>
      SyncTvService.adminSendTestEmail(to);

  @override
  Future<void> adminSetProviderInstanceEnabled(String name, bool enabled) =>
      SyncTvService.adminSetProviderInstanceEnabled(name, enabled);

  @override
  Future<void> adminSetRoomMemberRole(
    String roomId,
    String userId,
    common_enum.RoomMemberRole role,
  ) => SyncTvService.adminSetRoomMemberRole(roomId, userId, role);

  @override
  Future<void> adminUpdatePassword(
    String userId,
    String password, {
    String reason = '',
  }) => SyncTvService.adminUpdatePassword(userId, password, reason: reason);

  @override
  Future<AdminProviderInstance> adminUpdateProviderInstance({
    required String name,
    String? endpoint,
    String? comment,
    int? timeoutSeconds,
    bool? tls,
    bool? insecureTls,
    List<String> providers = const [],
    String? jwtSecret,
    String? customCa,
    bool? clearComment,
    bool? clearJwtSecret,
    bool? clearCustomCa,
  }) => SyncTvService.adminUpdateProviderInstance(
    name: name,
    endpoint: endpoint,
    comment: comment,
    timeoutSeconds: timeoutSeconds,
    tls: tls,
    insecureTls: insecureTls,
    providers: providers,
    jwtSecret: jwtSecret,
    customCa: customCa,
    clearComment: clearComment,
    clearJwtSecret: clearJwtSecret,
    clearCustomCa: clearCustomCa,
  );

  @override
  Future<void> adminUpdateRoomMemberDisplayTag(
    String roomId,
    String userId,
    String displayTag,
  ) =>
      SyncTvService.adminUpdateRoomMemberDisplayTag(roomId, userId, displayTag);

  @override
  Future<void> adminUpdateRoomMemberPermissionOverrides(
    String roomId,
    String userId, {
    common_enum.RoomMemberRole role =
        common_enum.RoomMemberRole.ROOM_MEMBER_ROLE_MEMBER,
    int addedPermissions = 0,
    int removedPermissions = 0,
    int adminAddedPermissions = 0,
    int adminRemovedPermissions = 0,
  }) => SyncTvService.adminUpdateRoomMemberPermissionOverrides(
    roomId,
    userId,
    role: role,
    addedPermissions: addedPermissions,
    removedPermissions: removedPermissions,
    adminAddedPermissions: adminAddedPermissions,
    adminRemovedPermissions: adminRemovedPermissions,
  );

  @override
  Future<void> adminUpdateRoomMemberRemarkName(
    String roomId,
    String userId,
    String remarkName,
  ) =>
      SyncTvService.adminUpdateRoomMemberRemarkName(roomId, userId, remarkName);

  @override
  Future<void> adminUpdateRoomPassword(String roomId, String password) =>
      SyncTvService.adminUpdateRoomPassword(roomId, password);

  @override
  Future<void> adminUpdateRoomSettings(
    String roomId,
    SyncTvRoomSettings settings,
  ) => SyncTvService.adminUpdateRoomSettings(roomId, settings);

  @override
  Future<SyncTvRoom> adminUpdateRoomTaxonomy(
    String roomId, {
    String? categoryId,
    List<String> labelIds = const [],
    bool clearCategory = false,
  }) => SyncTvService.adminUpdateRoomTaxonomy(
    roomId,
    categoryId: categoryId,
    labelIds: labelIds,
    clearCategory: clearCategory,
  );

  @override
  Future<AccountPreferences> adminUpdateUserPreferences(
    String userId, {
    bool? twoFactorEnabled,
    NotificationPreferences? notifications,
  }) => SyncTvService.adminUpdateUserPreferences(
    userId,
    twoFactorEnabled: twoFactorEnabled,
    notifications: notifications,
  );

  @override
  Future<void> adminUpdateUsername(String userId, String username) =>
      SyncTvService.adminUpdateUsername(userId, username);

  @override
  Future<RoomCategoryInfo> adminUpsertRoomCategory({
    required String key,
    required String name,
    String description = '',
    int sortOrder = 0,
    bool? isEnabled,
  }) => SyncTvService.adminUpsertRoomCategory(
    key: key,
    name: name,
    description: description,
    sortOrder: sortOrder,
    isEnabled: isEnabled,
  );

  @override
  Future<RoomLabelInfo> adminUpsertRoomLabel({
    required String key,
    required String name,
    String description = '',
    String color = '',
    String categoryId = '',
    int sortOrder = 0,
    bool? isEnabled,
  }) => SyncTvService.adminUpsertRoomLabel(
    key: key,
    name: name,
    description: description,
    color: color,
    categoryId: categoryId,
    sortOrder: sortOrder,
    isEnabled: isEnabled,
  );

  @override
  Future<RoomChatMessageInfo> deleteChatMessage(
    String roomId,
    String messageId, {
    required int expectedVersion,
    String reason = '',
  }) => SyncTvService.deleteChatMessage(
    roomId,
    messageId,
    expectedVersion: expectedVersion,
    reason: reason,
  );

  @override
  Future<ChatHistoryPage> getChatHistory(
    String roomId, {
    int limit = 50,
    String cursor = '',
    List<client_enum.ChatMessageType> includeMessageTypes =
        chatTimelineMessageTypes,
  }) => SyncTvService.getChatHistory(
    roomId,
    limit: limit,
    cursor: cursor,
    includeMessageTypes: includeMessageTypes,
  );

  @override
  Future<ChatMessageContextInfo> getChatMessageContext(
    String roomId,
    String messageId, {
    int beforeLimit = 20,
    int afterLimit = 20,
    bool includeDeleted = false,
  }) => SyncTvService.getChatMessageContext(
    roomId,
    messageId,
    beforeLimit: beforeLimit,
    afterLimit: afterLimit,
    includeDeleted: includeDeleted,
  );

  @override
  Future<SyncTvUser> getMe({bool refresh = false}) =>
      SyncTvService.getMe(refresh: refresh);

  @override
  Future<List<String>> listProviderBackends(String providerType) =>
      SyncTvService.listProviderBackends(providerType);

  @override
  Future<String> reportChatMessage(
    String roomId,
    String messageId, {
    required String reasonCode,
    String reason = '',
  }) => SyncTvService.reportChatMessage(
    roomId,
    messageId,
    reasonCode: reasonCode,
    reason: reason,
  );

  @override
  Future<RuntimeSettingsModel> runtimeGetSettings({bool refresh = false}) =>
      SyncTvService.runtimeGetSettings(refresh: refresh);

  @override
  Future<RuntimeSettingsSection> runtimeUpdateSettingInSection(
    String section,
    String key,
    dynamic value,
  ) => SyncTvService.runtimeUpdateSettingInSection(section, key, value);
}
