name: synctv_opaque
description: SyncTV OPAQUE client primitives.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.13.2

dependencies:
  code_assets: ^2.0.0
  cryptography: ^2.9.0
  ffi: ^2.2.0
  hooks: ^2.2.0
  ristretto255: ^1.0.2
  web: ^1.1.1

dev_dependencies:
  test: ^1.31.2

flutter:
  assets:
    - assets/synctv_opaque.wasm
