name: synctv_opaque
description: SyncTV OPAQUE client primitives.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.0

dependencies:
  code_assets: ^1.1.0
  ffi: ^2.1.3
  hooks: ^2.0.0

dev_dependencies:
  test: ^1.26.2
