// Generated by tool/generate_feature_gateways.dart.
import 'package:synctv_app/contracts/synctv_api_types.dart';
import 'package:synctv_app/src/generated/proto/admin.pbenum.dart' as admin_enum;
import 'package:synctv_app/src/generated/proto/client.pbenum.dart'
    as client_enum;
import 'package:synctv_app/src/generated/proto/common.pbenum.dart'
    as common_enum;
import 'package:synctv_app/src/generated/proto/providers/common.pbenum.dart'
    as provider_common_enum;

abstract interface class AdminGateway {
  Future<void> adminAddAdmin(String userId);

  Future<AdminProviderInstance> adminAddProviderInstance({
    required String name,
    required String endpoint,
    required List<String> providers,
    String comment = '',
    int timeoutSeconds = 30,
    bool tls = true,
    bool insecureTls = false,
    String? jwtSecret,
    String? customCa,
  });

  Future<void> adminAddRoomMember(
    String roomId,
    String userId, {
    common_enum.RoomMemberRole role =
        common_enum.RoomMemberRole.ROOM_MEMBER_ROLE_ADMIN,
    bool notify = true,
  });

  Future<void> adminAddUser(
    String username,
    String password,
    common_enum.UserRole role, {
    String email = '',
    common_enum.UserStatus status = common_enum.UserStatus.USER_STATUS_ACTIVE,
  });

  Future<void> adminApproveReview(AdminReviewKind kind, String requestId);

  Future<void> adminBanRoom(String roomId, bool ban, {String reason = ''});

  Future<void> adminBanUser(String userId, bool ban, {String reason = ''});

  Future<AdminBatchOperationResult> adminBatchBanRooms(
    List<String> roomIds, {
    String reason = '',
  });

  Future<AdminBatchOperationResult> adminBatchBanUsers(
    List<String> userIds, {
    String reason = '',
  });

  Future<AdminBatchOperationResult> adminBatchDeleteRooms(List<String> roomIds);

  Future<AdminBatchOperationResult> adminBatchDeleteUsers(List<String> userIds);

  Future<void> adminDeleteProviderInstance(String name);

  Future<void> adminDeleteRoom(String roomId);

  Future<void> adminDeleteRoomCategory(String categoryId);

  Future<void> adminDeleteRoomLabel(String labelId);

  Future<void> adminDeleteUser(String userId);

  Future<AdminSliceCacheOperationResult> adminEvictExpiredSliceCache({
    String nodeId = '',
    bool allNodes = false,
  });

  Future<SyncTvRoom> adminGetRoom(String roomId);

  Future<SyncTvRoomSettings> adminGetRoomSettings(
    String roomId, {
    bool refresh = false,
  });

  Future<AdminServiceState> adminGetServiceState();

  Future<AdminSliceCacheStats> adminGetSliceCacheStats({
    String nodeId = '',
    bool allNodes = false,
  });

  Future<SyncTvUser> adminGetUser(String userId);

  Future<AccountPreferences> adminGetUserPreferences(String userId);

  Future<void> adminKickRoomMember(
    String roomId,
    String userId, {
    int kickCooldownSeconds = 60,
  });

  Future<void> adminKickStream(AdminActiveStream stream);

  Future<AdminActiveStreamsPage> adminListActiveStreamsPage({
    int page = 1,
    int pageSize = 50,
    String roomId = '',
    String userId = '',
    String nodeId = '',
    String search = '',
    admin_enum.ActiveStreamListSortBy sortBy =
        admin_enum.ActiveStreamListSortBy.ACTIVE_STREAM_LIST_SORT_BY_STARTED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  });

  Future<AdminsPage> adminListAdminsPage({
    int page = 1,
    int pageSize = 20,
    String search = '',
    admin_enum.UserListSortBy sortBy =
        admin_enum.UserListSortBy.USER_LIST_SORT_BY_CREATED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  });

  Future<AdminBanRecordsPage> adminListBanRecordsPage({
    int page = 1,
    int pageSize = 50,
    admin_enum.BanTargetType targetType =
        admin_enum.BanTargetType.BAN_TARGET_TYPE_UNSPECIFIED,
    bool? active,
    String userId = '',
    String roomId = '',
  });

  Future<AdminProviderInstancesPage> adminListProviderInstancesPage({
    int page = 1,
    int pageSize = 50,
    String providerType = '',
    String search = '',
    bool? enabled,
    bool? tls,
    provider_common_enum.ProviderInstanceListSortBy sortBy =
        provider_common_enum
            .ProviderInstanceListSortBy
            .PROVIDER_INSTANCE_LIST_SORT_BY_NAME,
    provider_common_enum.SortDirection sortDirection =
        provider_common_enum.SortDirection.SORT_DIRECTION_ASC,
  });

  Future<AdminReviewsPage> adminListReviewsPage({
    required AdminReviewKind kind,
    int page = 1,
    int pageSize = 50,
    common_enum.ReviewStatus status =
        common_enum.ReviewStatus.REVIEW_STATUS_PENDING,
    String search = '',
    String requestedBy = '',
    String roomId = '',
    String userId = '',
  });

  Future<List<RoomCategoryInfo>> adminListRoomCategories({
    bool includeDisabled = false,
    bool refresh = false,
  });

  Future<List<RoomLabelInfo>> adminListRoomLabels({
    bool includeDisabled = false,
    String categoryId = '',
    bool refresh = false,
  });

  Future<AdminRoomMembersPage> adminListRoomMembersPage(
    String roomId, {
    int page = 1,
    int pageSize = 100,
    String search = '',
    common_enum.RoomMemberRole? role,
    admin_enum.RoomMemberListSortBy sortBy =
        admin_enum.RoomMemberListSortBy.ROOM_MEMBER_LIST_SORT_BY_JOINED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  });

  Future<AdminRoomsPage> adminListRoomsPage({
    int page = 1,
    int pageSize = 20,
    String? search,
    String categoryId = '',
    List<String> labelIds = const [],
    common_enum.RoomStatus status =
        common_enum.RoomStatus.ROOM_STATUS_UNSPECIFIED,
    bool? isBanned,
    admin_enum.RoomListSortBy sortBy =
        admin_enum.RoomListSortBy.ROOM_LIST_SORT_BY_CREATED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  });

  Future<AdminRoomsPage> adminListUserRoomsPage(
    String userId, {
    int page = 1,
    int pageSize = 20,
    String search = '',
    common_enum.RoomStatus status =
        common_enum.RoomStatus.ROOM_STATUS_UNSPECIFIED,
    bool? isBanned,
    admin_enum.RoomListSortBy sortBy =
        admin_enum.RoomListSortBy.ROOM_LIST_SORT_BY_CREATED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  });

  Future<AdminUsersPage> adminListUsersPage({
    int page = 1,
    int pageSize = 20,
    String? search,
    common_enum.UserStatus status =
        common_enum.UserStatus.USER_STATUS_UNSPECIFIED,
    common_enum.UserRole role = common_enum.UserRole.USER_ROLE_UNSPECIFIED,
    bool? isBanned,
    admin_enum.UserListSortBy sortBy =
        admin_enum.UserListSortBy.USER_LIST_SORT_BY_CREATED_AT,
    admin_enum.SortDirection sortDirection =
        admin_enum.SortDirection.SORT_DIRECTION_DESC,
  });

  Future<void> adminModerateRoomChatUser(
    String roomId,
    String userId, {
    required bool deleteAllMessages,
    required bool deleteAllReactions,
    required bool ban,
    String messageId = '',
    String reason = '',
  });

  Future<AdminSliceCacheOperationResult> adminPurgeSliceCache({
    String nodeId = '',
    bool allNodes = false,
  });

  Future<void> adminReconnectProviderInstance(String name);

  Future<void> adminRejectReview(
    AdminReviewKind kind,
    String requestId, {
    String reason = '',
  });

  Future<void> adminRemoveAdmin(String userId);

  Future<void> adminResetRoomSettings(String roomId);

  Future<String> adminSendTestEmail(String to);

  Future<void> adminSetProviderInstanceEnabled(String name, bool enabled);

  Future<void> adminSetRoomMemberRole(
    String roomId,
    String userId,
    common_enum.RoomMemberRole role,
  );

  Future<void> adminUpdatePassword(
    String userId,
    String password, {
    String reason = '',
  });

  Future<AdminProviderInstance> adminUpdateProviderInstance({
    required String name,
    String? endpoint,
    String? comment,
    int? timeoutSeconds,
    bool? tls,
    bool? insecureTls,
    List<String> providers = const [],
    String? jwtSecret,
    String? customCa,
    bool? clearComment,
    bool? clearJwtSecret,
    bool? clearCustomCa,
  });

  Future<void> adminUpdateRoomMemberDisplayTag(
    String roomId,
    String userId,
    String displayTag,
  );

  Future<void> adminUpdateRoomMemberPermissionOverrides(
    String roomId,
    String userId, {
    common_enum.RoomMemberRole role =
        common_enum.RoomMemberRole.ROOM_MEMBER_ROLE_MEMBER,
    int addedPermissions = 0,
    int removedPermissions = 0,
    int adminAddedPermissions = 0,
    int adminRemovedPermissions = 0,
  });

  Future<void> adminUpdateRoomMemberRemarkName(
    String roomId,
    String userId,
    String remarkName,
  );

  Future<void> adminUpdateRoomPassword(String roomId, String password);

  Future<void> adminUpdateRoomSettings(
    String roomId,
    SyncTvRoomSettings settings,
  );

  Future<SyncTvRoom> adminUpdateRoomTaxonomy(
    String roomId, {
    String? categoryId,
    List<String> labelIds = const [],
    bool clearCategory = false,
  });

  Future<AccountPreferences> adminUpdateUserPreferences(
    String userId, {
    bool? twoFactorEnabled,
    NotificationPreferences? notifications,
  });

  Future<void> adminUpdateUsername(String userId, String username);

  Future<RoomCategoryInfo> adminUpsertRoomCategory({
    required String key,
    required String name,
    String description = '',
    int sortOrder = 0,
    bool? isEnabled,
  });

  Future<RoomLabelInfo> adminUpsertRoomLabel({
    required String key,
    required String name,
    String description = '',
    String color = '',
    String categoryId = '',
    int sortOrder = 0,
    bool? isEnabled,
  });

  Future<RoomChatMessageInfo> deleteChatMessage(
    String roomId,
    String messageId, {
    required int expectedVersion,
    String reason = '',
  });

  Future<ChatHistoryPage> getChatHistory(
    String roomId, {
    int limit = 50,
    String cursor = '',
    List<client_enum.ChatMessageType> includeMessageTypes =
        chatTimelineMessageTypes,
  });

  Future<ChatMessageContextInfo> getChatMessageContext(
    String roomId,
    String messageId, {
    int beforeLimit = 20,
    int afterLimit = 20,
    bool includeDeleted = false,
  });

  Future<SyncTvUser> getMe({bool refresh = false});

  Future<List<String>> listProviderBackends(String providerType);

  Future<String> reportChatMessage(
    String roomId,
    String messageId, {
    required String reasonCode,
    String reason = '',
  });

  Future<RuntimeSettingsModel> runtimeGetSettings({bool refresh = false});

  Future<RuntimeSettingsSection> runtimeUpdateSettingInSection(
    String section,
    String key,
    dynamic value,
  );
}
