import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:flutter_test/flutter_test.dart';

import '../../tool/frontend_audit_inventory.dart';
import '../../tool/frontend_audit_inventory.dart' as inventory;

void main() {
  late Directory root;

  void write(String path, String value) {
    File('${root.path}/$path')
      ..createSync(recursive: true)
      ..writeAsStringSync(value);
  }

  void ledger(Map<String, dynamic> files) =>
      write('docs/frontend-audit.json', jsonEncode({'files': files}));

  setUp(() {
    root = Directory.systemTemp.createTempSync('frontend-audit-');
    ledger({});
  });
  tearDown(() => root.deleteSync(recursive: true));

  test('check mode fails stale inventories and passes regenerated output', () {
    final previousDirectory = Directory.current;
    final previousExitCode = exitCode;
    try {
      Directory.current = root;
      write('lib/main.dart', 'void main() {}\n');
      exitCode = 0;
      inventory.main(['--check']);
      expect(exitCode, 1);

      exitCode = 0;
      inventory.main([]);
      inventory.main(['--check']);
      expect(exitCode, 0);

      write('lib/added.dart', 'class Added {}\n');
      inventory.main(['--check']);
      expect(exitCode, 1);

      exitCode = 0;
      inventory.main([]);
      inventory.main(['--check']);
      expect(exitCode, 0);
      expect(
        File('docs/frontend-audit-inventory.md').readAsStringSync(),
        contains('lib/added.dart'),
      );
    } finally {
      Directory.current = previousDirectory;
      exitCode = previousExitCode;
    }
  });

  test('inventory includes companion sources and excludes generated/cache/test trees', () {
    write('lib/features/auth/presentation/login.dart', 'class Login {}\n');
    write('web/startup.js', 'start();\n');
    write('packages/local/src/lib.rs', 'fn main() {}\n');
    write('ios/Runner/AppDelegate.swift', 'import Foundation\n');
    write('tool/check.dart', 'void main() {}\n');
    write('tool/subset_font.py', 'print("font coverage")\n');
    write('packages/local/build/cached.dart', 'cached\n');
    write('packages/local/test/unit.dart', 'test\n');
    write('lib/src/generated/api.dart', 'generated\n');
    write(
      'lib/features/auth/application/gateway.dart',
      '// Generated by tool/generator.dart.\n',
    );
    write('web/playback/hls.min.js', 'vendored\n');
    final result = buildFrontendAuditInventory(root);
    expect(result, contains('Indexed handwritten/support sources: 6 files'));
    expect(result, contains('[tool/subset_font.py]'));
    expect(result, contains('[web/startup.js]'));
    expect(result, contains('[packages/local/src/lib.rs]'));
    expect(result, contains('[ios/Runner/AppDelegate.swift]'));
    expect(result, isNot(contains('cached.dart')));
    expect(result, isNot(contains('unit.dart')));
    expect(result, contains('Generated sources (2 files)'));
    expect(result, contains('Vendored browser bundles (1 files)'));
    expect(result, buildFrontendAuditInventory(root));
  });

  test(
    'source changes invalidate review while new files remain unreviewed',
    () {
      const source = 'void main() {}\n';
      write('lib/main.dart', source);
      write('test/main_test.dart', 'test evidence');
      ledger({
        'lib/main.dart': {
          'state': 'reviewed',
          'sha256': sha256.convert(utf8.encode(source)).toString(),
          'scope': 'Startup | lifecycle',
          'evidence': ['test/main_test.dart'],
        },
      });
      expect(
        buildFrontendAuditInventory(root),
        contains('| 1 | reviewed | Startup \\| lifecycle'),
      );
      write('lib/main.dart', 'void main() { run(); }\n');
      write('lib/new.dart', '// newly added\n');
      final result = buildFrontendAuditInventory(root);
      expect(result, contains('| 1 | needs-review |'));
      expect(
        result,
        contains('[lib/new.dart](../lib/new.dart) | 1 | unreviewed |'),
      );
    },
  );

  test('missing evidence and orphaned source records cannot silently pass', () {
    const source = 'void main() {}\n';
    write('lib/main.dart', source);
    ledger({
      'lib/main.dart': {
        'state': 'partial',
        'sha256': sha256.convert(utf8.encode(source)).toString(),
        'scope': 'Startup',
        'evidence': ['test/missing.dart'],
      },
    });
    expect(() => buildFrontendAuditInventory(root), throwsFormatException);
    write('test/missing.dart', 'evidence');
    File('${root.path}/lib/main.dart').deleteSync();
    expect(() => buildFrontendAuditInventory(root), throwsFormatException);
  });
}
