import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const _roots = [
  'lib',
  'web',
  'android/app/src',
  'ios/Runner',
  'macos/Runner',
  'linux/runner',
  'windows/runner',
  'packages',
  'tool',
];
const _extensions = {
  'dart',
  'js',
  'mjs',
  'html',
  'css',
  'kt',
  'java',
  'swift',
  'm',
  'mm',
  'h',
  'c',
  'cc',
  'cpp',
  'rs',
  'sh',
  'ps1',
  'py',
};
const _ignoredDirectories = {
  '.dart_tool',
  '.git',
  'build',
  'target',
  'node_modules',
  'test',
  'tests',
  'Pods',
  '.symlinks',
  '.build',
};

String buildFrontendAuditInventory(Directory root) {
  final ledger = jsonDecode(
    File('${root.path}/docs/frontend-audit.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final records = ledger['files'] as Map<String, dynamic>;
  final rows =
      <
        ({
          String path,
          String owner,
          int lines,
          String state,
          String scope,
          List<String> evidence,
        })
      >[];
  final excluded = <String, List<String>>{};
  final discovered = <String>{};

  Iterable<File> walk(Directory directory) sync* {
    if (!directory.existsSync()) return;
    for (final entry in directory.listSync(followLinks: false)) {
      final name = entry.uri.pathSegments.where((part) => part.isNotEmpty).last;
      if (entry is Directory && !_ignoredDirectories.contains(name)) {
        yield* walk(entry);
      } else if (entry is File && _extensions.contains(name.split('.').last)) {
        yield entry;
      }
    }
  }

  for (final sourceRoot in _roots) {
    for (final file in walk(Directory('${root.path}/$sourceRoot'))) {
      final path = file.path
          .substring(root.path.length + 1)
          .replaceAll('\\', '/');
      final bytes = file.readAsBytesSync();
      final content = utf8.decode(bytes);
      final reason = _exclusion(path, content);
      if (reason != null) {
        (excluded[reason] ??= []).add(path);
        continue;
      }
      discovered.add(path);
      final record = records[path] as Map<String, dynamic>?;
      final evidence =
          (record?['evidence'] as List?)?.cast<String>() ?? <String>[];
      if (record != null) {
        if (!{'partial', 'reviewed'}.contains(record['state']) ||
            (record['scope'] as String? ?? '').isEmpty ||
            evidence.isEmpty ||
            !RegExp(r'^[a-f0-9]{64}$')
                .hasMatch(record['sha256'] as String? ?? '')) {
          throw FormatException('Invalid audit record: $path');
        }
        for (final item in evidence) {
          if (Uri.parse(item).isAbsolute ||
              item.split('/').contains('..') ||
              !File('${root.path}/$item').existsSync()) {
            throw FormatException(
              'Missing or invalid evidence for $path: $item',
            );
          }
        }
      }
      final state = record == null
          ? 'unreviewed'
          : record['sha256'] == sha256.convert(bytes).toString()
          ? record['state'] as String
          : 'needs-review';
      final parts = path.split('/');
      final owner = parts.first == 'lib' && parts[1] == 'features'
          ? 'features/${parts[2]}'
          : parts.first == 'lib'
          ? parts[1] == 'main.dart'
                ? 'entrypoint'
                : parts[1]
          : parts.first == 'packages'
          ? 'packages/${parts[1]}'
          : parts.first;
      rows.add((
        path: path,
        owner: owner,
        lines: const LineSplitter().convert(content).length,
        state: state,
        scope: record?['scope'] as String? ?? '',
        evidence: evidence,
      ));
    }
  }
  final missing = records.keys.toSet().difference(discovered);
  if (missing.isNotEmpty)
    throw FormatException(
      'Audit records reference missing/excluded sources: ${missing.join(', ')}',
    );
  rows.sort((a, b) => a.path.compareTo(b.path));
  final output = StringBuffer('''# Frontend Source Audit Inventory

Generated by `dart run tool/frontend_audit_inventory.dart`.
Manual evidence lives in [frontend-audit.json](frontend-audit.json).

This inventory covers runtime source and maintenance scripts in the configured
source roots. Dedicated test directories, generated output, vendored bundles, assets and build caches
are not handwritten runtime review claims. Configuration, dependency, UI-state,
device and performance audits remain separate requirements in
[frontend-modernization.md](frontend-modernization.md).

`unreviewed` means no file-specific record is registered, even if an earlier
workflow exercised it. `partial` records only the stated scope. `reviewed` means
the recorded source scope was examined, not that every device/integration was
tested. `needs-review` means the source fingerprint changed since that record.
Test-file links identify evidence to inspect; their existence does not prove a
passing run or complete behavioral coverage.

Indexed handwritten/support sources: ${rows.length} files,
${rows.fold<int>(0, (sum, row) => sum + row.lines)} lines.

## Modules

| Module | Files | Lines | Unreviewed | Partial | Reviewed | Needs Review |
| --- | ---: | ---: | ---: | ---: | ---: | ---: |
''');
  final owners = rows.map((row) => row.owner).toSet().toList()..sort();
  for (final owner in owners) {
    final group = rows.where((row) => row.owner == owner).toList();
    output.writeln(
      '| $owner | ${group.length} | ${group.fold<int>(0, (sum, row) => sum + row.lines)} | ${['unreviewed', 'partial', 'reviewed', 'needs-review'].map((state) => group.where((row) => row.state == state).length).join(' | ')} |',
    );
  }
  output.writeln(
    '\n## Files\n\n| Source | Lines | State | Scope | Evidence |\n| --- | ---: | --- | --- | --- |',
  );
  for (final row in rows) {
    output.writeln(
      '| [${row.path}](../${row.path}) | ${row.lines} | ${row.state} | ${row.scope.replaceAll('|', '\\|').replaceAll('\n', ' ')} | ${row.evidence.map((path) => '[${path.split('/').last}](../$path)').join(', ')} |',
    );
  }
  output.writeln('\n## Excluded Sources\n');
  for (final reason in excluded.keys.toList()..sort()) {
    final paths = excluded[reason]!..sort();
    output.writeln(
      '<details><summary>$reason (${paths.length} files)</summary>\n',
    );
    for (final path in paths) {
      output.writeln('- `$path`');
    }
    output.writeln('\n</details>\n');
  }
  return output.toString();
}

String? _exclusion(String path, String content) {
  if (path.startsWith('web/playback/') || path == 'web/passkeys_bundle.js')
    return 'Vendored browser bundles';
  if (path.startsWith('lib/src/generated/') ||
      path.startsWith('lib/l10n/app_localizations') ||
      path.endsWith('.g.dart') ||
      path.contains('GeneratedPluginRegistrant.') ||
      content.startsWith('// Generated by ') ||
      content.startsWith('// Autogenerated from Pigeon'))
    return 'Generated sources';
  return null;
}

void main(List<String> args) {
  if (args.any((arg) => arg != '--check')) {
    stderr.writeln(
      'Usage: dart run tool/frontend_audit_inventory.dart [--check]',
    );
    exitCode = 2;
    return;
  }
  final report = buildFrontendAuditInventory(Directory.current);
  final output = File('docs/frontend-audit-inventory.md');
  if (args.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != report) {
      stderr.writeln('Frontend audit inventory is stale; regenerate it.');
      exitCode = 1;
    } else {
      stdout.writeln('Frontend audit inventory is current.');
    }
  } else {
    output.writeAsStringSync(report);
    stdout.writeln('Updated ${output.path}');
  }
}
