import 'dart:io';

final _serviceFile = File('lib/data/synctv_api/synctv_service.dart');

void main(List<String> args) {
  generateFeatureGateways(check: args.contains('--check'));
}

void generateFeatureGateways({bool check = false}) {
  final source = _serviceFile.readAsStringSync();
  _generate(
    source: source,
    className: 'AdminGateway',
    methods: _adminMethods,
    interfacePath: 'lib/features/admin/application/admin_gateway.dart',
    adapterPath: 'lib/features/admin/data/synctv_admin_gateway.dart',
    adapterClassName: 'SyncTvAdminGateway',
    check: check,
  );
  _generate(
    source: source,
    className: 'ProviderGateway',
    methods: _providerMethods,
    interfacePath: 'lib/features/providers/application/provider_gateway.dart',
    adapterPath: 'lib/features/providers/data/synctv_provider_gateway.dart',
    adapterClassName: 'SyncTvProviderGateway',
    check: check,
  );
}

void _generate({
  required String source,
  required String className,
  required Set<String> methods,
  required String interfacePath,
  required String adapterPath,
  required String adapterClassName,
  required bool check,
}) {
  final declarations = <_MethodDeclaration>[];
  for (final method in methods.toList()..sort()) {
    try {
      declarations.add(_extractMethod(source, method));
    } catch (error) {
      throw StateError('Failed to generate $className.$method: $error');
    }
  }
  final aliases = <String>{
    for (final declaration in declarations)
      ...RegExp(
        r'\b([a-z][A-Za-z0-9_]*)\.',
      ).allMatches(declaration.signature).map((match) => match.group(1)!),
  };
  final aliasImports = <String>[];
  for (final alias in aliases.toList()..sort()) {
    final match = RegExp(
      "import '([^']+)'\\s+as $alias;",
      multiLine: true,
    ).firstMatch(source);
    if (match == null) {
      throw StateError('Missing import for alias $alias in $className');
    }
    aliasImports.add("import '${match.group(1)}' as $alias;");
  }

  final imports = [
    "import 'package:synctv_app/contracts/synctv_api_types.dart';",
    ...aliasImports,
  ].join('\n');
  final interface = StringBuffer()
    ..writeln('// Generated by tool/generate_feature_gateways.dart.')
    ..writeln(imports)
    ..writeln()
    ..writeln('abstract interface class $className {');
  for (final declaration in declarations) {
    interface
      ..writeln('  ${declaration.signature};')
      ..writeln();
  }
  interface.writeln('}');

  final adapter = StringBuffer()
    ..writeln('// Generated by tool/generate_feature_gateways.dart.')
    ..writeln("import 'package:synctv_app/${interfacePath.substring(4)}';")
    ..writeln(
      "import 'package:synctv_app/data/synctv_api/synctv_service.dart';",
    )
    ..writeln(imports)
    ..writeln()
    ..writeln('final class $adapterClassName implements $className {')
    ..writeln('  const $adapterClassName();')
    ..writeln();
  for (final declaration in declarations) {
    adapter
      ..writeln('  @override')
      ..writeln('  ${declaration.signature} =>')
      ..writeln(
        '      SyncTvService.${declaration.name}(${declaration.forwardedArguments});',
      )
      ..writeln();
  }
  adapter.writeln('}');

  _writeGenerated(interfacePath, _formatDart(interface.toString()), check);
  _writeGenerated(adapterPath, _formatDart(adapter.toString()), check);
}

_MethodDeclaration _extractMethod(String source, String name) {
  final starts = RegExp(r'^  static ', multiLine: true).allMatches(source);
  for (final start in starts) {
    final next = source.indexOf('\n  static ', start.end);
    final segment = source.substring(
      start.start,
      next < 0 ? source.length : next,
    );
    final nameMatch = RegExp(
      '\\b${RegExp.escape(name)}\\s*\\(',
    ).firstMatch(segment);
    if (nameMatch == null) continue;
    final openParen = segment.indexOf('(', nameMatch.start);
    final closeParen = _matchingParen(segment, openParen);
    var signatureEnd = closeParen + 1;
    while (signatureEnd < segment.length &&
        _isWhitespace(segment.codeUnitAt(signatureEnd))) {
      signatureEnd++;
    }
    if (segment.startsWith('async', signatureEnd)) {
      signatureEnd += 5;
    }
    final rawSignature = segment
        .substring('  static '.length, closeParen + 1)
        .trim();
    final parameters = segment.substring(openParen + 1, closeParen);
    return _MethodDeclaration(
      name: name,
      signature: rawSignature,
      forwardedArguments: _forwardArguments(parameters),
    );
  }
  throw StateError('Unable to find SyncTvService.$name');
}

int _matchingParen(String source, int open) {
  var depth = 0;
  for (var index = open; index < source.length; index++) {
    switch (source[index]) {
      case '(':
        depth++;
      case ')':
        depth--;
        if (depth == 0) return index;
    }
  }
  throw FormatException('Unmatched method parameter list');
}

String _forwardArguments(String parameters) {
  final parts = <({String value, bool named})>[];
  final buffer = StringBuffer();
  var named = false;
  var round = 0;
  var square = 0;
  var curly = 0;
  var angle = 0;
  String? quote;
  var escaped = false;
  void flush() {
    final value = buffer.toString().trim();
    buffer.clear();
    if (value.isNotEmpty) parts.add((value: value, named: named));
  }

  for (var index = 0; index < parameters.length; index++) {
    final char = parameters[index];
    if (quote != null) {
      buffer.write(char);
      if (escaped) {
        escaped = false;
      } else if (char == '\\') {
        escaped = true;
      } else if (char == quote) {
        quote = null;
      }
      continue;
    }
    if (char == "'" || char == '"') {
      quote = char;
      buffer.write(char);
      continue;
    }
    if (round == 0 && square == 0 && curly == 0 && angle == 0) {
      if (char == '{' && buffer.toString().trim().isEmpty) {
        named = true;
        continue;
      }
      if (char == '[' && buffer.toString().trim().isEmpty) continue;
      if (char == '}' || char == ']') {
        flush();
        continue;
      }
      if (char == ',') {
        flush();
        continue;
      }
    }
    switch (char) {
      case '(':
        round++;
      case ')':
        round--;
      case '[':
        square++;
      case ']':
        square--;
      case '<':
        angle++;
      case '>':
        angle--;
      case '{':
        curly++;
      case '}':
        curly--;
    }
    buffer.write(char);
  }
  flush();

  return parts
      .map((part) {
        final withoutDefault = part.value.split('=').first.trim();
        final match = RegExp(
          r'([A-Za-z_][A-Za-z0-9_]*)\s*$',
        ).firstMatch(withoutDefault);
        if (match == null)
          throw FormatException('Cannot parse parameter: ${part.value}');
        final name = match.group(1)!;
        return part.named ? '$name: $name' : name;
      })
      .join(', ');
}

bool _isWhitespace(int codeUnit) =>
    codeUnit == 0x20 ||
    codeUnit == 0x09 ||
    codeUnit == 0x0A ||
    codeUnit == 0x0D;

String _formatDart(String content) {
  final directory = Directory.systemTemp.createTempSync('synctv_gateway_');
  try {
    final file = File('${directory.path}/generated.dart')
      ..writeAsStringSync(content);
    final result = Process.runSync('dart', ['format', file.path]);
    if (result.exitCode != 0) {
      throw StateError('dart format failed: ${result.stderr}');
    }
    return file.readAsStringSync();
  } finally {
    directory.deleteSync(recursive: true);
  }
}

void _writeGenerated(String path, String content, bool check) {
  final file = File(path);
  if (check) {
    if (!file.existsSync() || file.readAsStringSync() != content) {
      throw StateError('$path is stale; regenerate feature gateways.');
    }
    stdout.writeln('Checked $path');
    return;
  }
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(content);
  stdout.writeln('Generated $path');
}

const _adminMethods = <String>{
  'adminAddAdmin',
  'adminAddProviderInstance',
  'adminAddRoomMember',
  'adminAddUser',
  'adminApproveReview',
  'adminBanRoom',
  'adminBanUser',
  'adminBatchBanRooms',
  'adminBatchBanUsers',
  'adminBatchDeleteRooms',
  'adminBatchDeleteUsers',
  'adminDeleteProviderInstance',
  'adminDeleteRoom',
  'adminDeleteRoomCategory',
  'adminDeleteRoomLabel',
  'adminDeleteUser',
  'adminEvictExpiredSliceCache',
  'adminGetRoom',
  'adminGetRoomSettings',
  'adminGetServiceState',
  'adminGetSliceCacheStats',
  'adminGetUser',
  'adminGetUserPreferences',
  'adminKickRoomMember',
  'adminKickStream',
  'adminListActiveStreamsPage',
  'adminListAdminsPage',
  'adminListBanRecordsPage',
  'adminListRoomCategories',
  'adminListRoomLabels',
  'adminListProviderInstancesPage',
  'adminListReviewsPage',
  'adminListRoomMembersPage',
  'adminListRoomsPage',
  'adminListUserRoomsPage',
  'adminModerateRoomChatUser',
  'adminListUsersPage',
  'adminPurgeSliceCache',
  'adminReconnectProviderInstance',
  'adminRejectReview',
  'adminRemoveAdmin',
  'adminResetRoomSettings',
  'adminSendTestEmail',
  'adminSetProviderInstanceEnabled',
  'adminSetRoomMemberRole',
  'adminUpdatePassword',
  'adminUpdateProviderInstance',
  'adminUpdateRoomMemberDisplayTag',
  'adminUpdateRoomMemberPermissionOverrides',
  'adminUpdateRoomMemberRemarkName',
  'adminUpdateRoomPassword',
  'adminUpdateRoomSettings',
  'adminUpdateRoomTaxonomy',
  'adminUpdateUserPreferences',
  'adminUpdateUsername',
  'adminUpsertRoomCategory',
  'adminUpsertRoomLabel',
  'deleteChatMessage',
  'getChatHistory',
  'getChatMessageContext',
  'getMe',
  'listProviderBackends',
  'reportChatMessage',
  'runtimeGetSettings',
  'runtimeUpdateSettingInSection',
};

const _providerMethods = <String>{
  'addDiscoveredSource',
  'bindDouyin',
  'bindTikTok',
  'bindTwitch',
  'bindYoutube',
  'checkBilibiliQrLogin',
  'createRtmpPublishKeyInfo',
  'getAlistAccount',
  'getAllAlistBindInfos',
  'getAllBilibiliBindInfos',
  'getAllCloudreveBindInfos',
  'getAllDouyinBindInfos',
  'getAllEmbyBindInfos',
  'getAllFnosBindInfos',
  'getAllNextcloudBindInfos',
  'getAllQnapBindInfos',
  'getAllSeafileBindInfos',
  'getAllSynologyBindInfos',
  'getAllTikTokBindInfos',
  'getAllTrueNasBindInfos',
  'getAllTwitchBindInfos',
  'getAllYoutubeBindInfos',
  'getBilibiliAccount',
  'getCloudreveAccount',
  'getEmbyAccount',
  'getPublicSettings',
  'getQnapCapabilities',
  'getRtmpStreamInfo',
  'getTikTokUser',
  'listAlistPage',
  'listAvailableProviderInstances',
  'listBilibiliFavoriteFolders',
  'listBilibiliFollowedPgc',
  'listBilibiliLiveAreas',
  'listBilibiliPgcSeasons',
  'listBilibiliPgcTimeline',
  'listBilibiliPlaylist',
  'listCloudrevePage',
  'listDouyinUserPosts',
  'listEmbyPage',
  'listFnosFiles',
  'listFnosMediaLibraries',
  'listFnosMediaItems',
  'listMediaLibrary',
  'listNextcloudFavorites',
  'listNextcloudFiles',
  'listQnapFiles',
  'listSeafileFiles',
  'listSeafileRepositories',
  'listSeafileStarred',
  'listSynologyFiles',
  'listSynologyLibraries',
  'listSynologyVideos',
  'listTikTokUserPosts',
  'listTrueNasFiles',
  'listTwitchCategoryStreams',
  'listTwitchChannelItems',
  'listTwitchFollowedLive',
  'listTwitchSchedule',
  'listTwitchTopCategories',
  'loginAList',
  'loginBilibiliSms',
  'loginCloudreve',
  'loginEmbyInfo',
  'loginFnos',
  'loginNextcloud',
  'loginQnap',
  'loginSeafile',
  'loginSynology',
  'loginTrueNas',
  'logoutAList',
  'logoutBilibili',
  'logoutCloudreve',
  'logoutEmby',
  'logoutFnos',
  'logoutNextcloud',
  'logoutQnap',
  'logoutSeafile',
  'logoutSynology',
  'logoutTrueNas',
  'parseBilibiliInfo',
  'prepareDirectUrl',
  'prepareLiveProxy',
  'prepareRtmp',
  'pollNextcloudLoginFlow',
  'resolveAcFun',
  'resolveCctv',
  'resolveDouyin',
  'resolveDouyu',
  'resolveHuya',
  'resolvePlaybackProxyPolicy',
  'resolveTikTok',
  'resolveTwitch',
  'resolveYoutube',
  'listYoutube',
  'searchTwitchLiveChannels',
  'sendBilibiliSms',
  'setFnosFavorite',
  'setFnosWatched',
  'startBilibiliQrLogin',
  'startBilibiliSmsLogin',
  'startNextcloudLoginFlow',
  'unbindDouyin',
  'unbindTikTok',
  'unbindTwitch',
  'unbindYoutube',
  'unlockSeafileLibrary',
};

final class _MethodDeclaration {
  const _MethodDeclaration({
    required this.name,
    required this.signature,
    required this.forwardedArguments,
  });

  final String name;
  final String signature;
  final String forwardedArguments;
}
