// Generated by tool/generate_feature_gateways.dart.
import 'package:synctv_app/features/providers/application/provider_gateway.dart';
import 'package:synctv_app/data/synctv_api/synctv_service.dart';
import 'package:synctv_app/contracts/synctv_api_types.dart';
import 'package:synctv_app/src/generated/proto/providers/acfun.pb.dart'
    as acfun;
import 'package:synctv_app/src/generated/proto/providers/bilibili.pbenum.dart'
    as bilibili_enum;
import 'package:synctv_app/src/generated/proto/providers/cctv.pb.dart' as cctv;
import 'package:synctv_app/src/generated/proto/client.pb.dart' as client;
import 'package:synctv_app/src/generated/proto/client.pbenum.dart'
    as client_enum;
import 'package:synctv_app/src/generated/proto/providers/douyin.pb.dart'
    as douyin;
import 'package:synctv_app/src/generated/proto/providers/douyu.pb.dart'
    as douyu;
import 'package:synctv_app/src/generated/proto/providers/huya.pb.dart' as huya;
import 'package:synctv_app/src/generated/proto/providers/common.pb.dart'
    as provider_common;
import 'package:synctv_app/src/generated/proto/source_config.pb.dart'
    as source_config;
import 'package:synctv_app/src/generated/proto/source_config.pbenum.dart'
    as source_enum;
import 'package:synctv_app/src/generated/proto/providers/tiktok.pb.dart'
    as tiktok;
import 'package:synctv_app/src/generated/proto/providers/twitch.pb.dart'
    as twitch;
import 'package:synctv_app/src/generated/proto/providers/youtube.pb.dart'
    as youtube;

final class SyncTvProviderGateway implements ProviderGateway {
  const SyncTvProviderGateway();

  @override
  Future<String> addDiscoveredSource(
    String roomId, {
    required provider_common.DiscoveredSource source,
    String playlistId = '',
    String name = '',
  }) => SyncTvService.addDiscoveredSource(
    roomId,
    source: source,
    playlistId: playlistId,
    name: name,
  );

  @override
  Future<DouyinBindInfo> bindDouyin({
    required String label,
    required String cookie,
    String instanceName = '',
  }) => SyncTvService.bindDouyin(
    label: label,
    cookie: cookie,
    instanceName: instanceName,
  );

  @override
  Future<TikTokBindInfo> bindTikTok({
    required String label,
    required String cookie,
    String instanceName = '',
  }) => SyncTvService.bindTikTok(
    label: label,
    cookie: cookie,
    instanceName: instanceName,
  );

  @override
  Future<TwitchBindInfo> bindTwitch({
    required String authToken,
    String deviceId = '',
    String clientIntegrity = '',
    String instanceName = '',
  }) => SyncTvService.bindTwitch(
    authToken: authToken,
    deviceId: deviceId,
    clientIntegrity: clientIntegrity,
    instanceName: instanceName,
  );

  @override
  Future<YoutubeBindInfo> bindYoutube({
    required String label,
    String visitorData = '',
    String poToken = '',
    String cookie = '',
    String instanceName = '',
  }) => SyncTvService.bindYoutube(
    label: label,
    visitorData: visitorData,
    poToken: poToken,
    cookie: cookie,
    instanceName: instanceName,
  );

  @override
  Future<bilibili_enum.QRLoginStatus> checkBilibiliQrLogin(
    String key, {
    String instanceName = '',
  }) => SyncTvService.checkBilibiliQrLogin(key, instanceName: instanceName);

  @override
  Future<RtmpPublishKeyInfo> createRtmpPublishKeyInfo(
    String roomId,
    String mediaId, {
    required client.PublishKeyType keyType,
    int? expiresAt,
  }) => SyncTvService.createRtmpPublishKeyInfo(
    roomId,
    mediaId,
    keyType: keyType,
    expiresAt: expiresAt,
  );

  @override
  Future<AlistAccountInfo> getAlistAccount(
    String serverId, {
    String instanceName = '',
  }) => SyncTvService.getAlistAccount(serverId, instanceName: instanceName);

  @override
  Future<List<AlistBindInfo>> getAllAlistBindInfos() =>
      SyncTvService.getAllAlistBindInfos();

  @override
  Future<List<BilibiliBindInfo>> getAllBilibiliBindInfos() =>
      SyncTvService.getAllBilibiliBindInfos();

  @override
  Future<List<CloudreveBindInfo>> getAllCloudreveBindInfos() =>
      SyncTvService.getAllCloudreveBindInfos();

  @override
  Future<List<DouyinBindInfo>> getAllDouyinBindInfos() =>
      SyncTvService.getAllDouyinBindInfos();

  @override
  Future<List<EmbyBindInfo>> getAllEmbyBindInfos() =>
      SyncTvService.getAllEmbyBindInfos();

  @override
  Future<List<FnosBindInfo>> getAllFnosBindInfos() =>
      SyncTvService.getAllFnosBindInfos();

  @override
  Future<List<NextcloudBindInfo>> getAllNextcloudBindInfos() =>
      SyncTvService.getAllNextcloudBindInfos();

  @override
  Future<List<QnapBindInfo>> getAllQnapBindInfos() =>
      SyncTvService.getAllQnapBindInfos();

  @override
  Future<List<SeafileBindInfo>> getAllSeafileBindInfos() =>
      SyncTvService.getAllSeafileBindInfos();

  @override
  Future<List<SynologyBindInfo>> getAllSynologyBindInfos() =>
      SyncTvService.getAllSynologyBindInfos();

  @override
  Future<List<TikTokBindInfo>> getAllTikTokBindInfos() =>
      SyncTvService.getAllTikTokBindInfos();

  @override
  Future<List<TrueNasBindInfo>> getAllTrueNasBindInfos() =>
      SyncTvService.getAllTrueNasBindInfos();

  @override
  Future<List<TwitchBindInfo>> getAllTwitchBindInfos() =>
      SyncTvService.getAllTwitchBindInfos();

  @override
  Future<List<YoutubeBindInfo>> getAllYoutubeBindInfos() =>
      SyncTvService.getAllYoutubeBindInfos();

  @override
  Future<BilibiliAccountInfo> getBilibiliAccount({String instanceName = ''}) =>
      SyncTvService.getBilibiliAccount(instanceName: instanceName);

  @override
  Future<CloudreveAccountInfo> getCloudreveAccount(
    String serverId, {
    String instanceName = '',
  }) => SyncTvService.getCloudreveAccount(serverId, instanceName: instanceName);

  @override
  Future<EmbyAccountInfo> getEmbyAccount(
    String serverId, {
    String instanceName = '',
  }) => SyncTvService.getEmbyAccount(serverId, instanceName: instanceName);

  @override
  Future<PublicSettingsInfo> getPublicSettings({bool refresh = false}) =>
      SyncTvService.getPublicSettings(refresh: refresh);

  @override
  Future<QnapCapabilitiesInfo> getQnapCapabilities(
    String serverId, {
    String instanceName = '',
  }) => SyncTvService.getQnapCapabilities(serverId, instanceName: instanceName);

  @override
  Future<RoomStreamEntryInfo> getRtmpStreamInfo({
    required String roomId,
    required String mediaId,
  }) => SyncTvService.getRtmpStreamInfo(roomId: roomId, mediaId: mediaId);

  @override
  Future<tiktok.GetUserResponse> getTikTokUser(
    String resource, {
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.getTikTokUser(
    resource,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<AlistListPage> listAlistPage(
    String path, {
    String? keyword,
    int page = 1,
    int max = 20,
    String password = '',
    String serverId = '',
    String instanceName = '',
  }) => SyncTvService.listAlistPage(
    path,
    keyword: keyword,
    page: page,
    max: max,
    password: password,
    serverId: serverId,
    instanceName: instanceName,
  );

  @override
  Future<List<String>> listAvailableProviderInstances({
    String providerType = '',
  }) =>
      SyncTvService.listAvailableProviderInstances(providerType: providerType);

  @override
  Future<List<BilibiliFavoriteFolderInfo>> listBilibiliFavoriteFolders({
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listBilibiliFavoriteFolders(
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<BilibiliFollowedPgcPage> listBilibiliFollowedPgc({
    required bool cinema,
    int page = 1,
    int pageSize = 30,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listBilibiliFollowedPgc(
    cinema: cinema,
    page: page,
    pageSize: pageSize,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<List<BilibiliLiveAreaInfo>> listBilibiliLiveAreas({
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listBilibiliLiveAreas(
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<BilibiliPgcSeasonPage> listBilibiliPgcSeasons({
    required BilibiliPgcSeasonKind type,
    int page = 1,
    int pageSize = 30,
    BilibiliPgcSeasonOrder order = BilibiliPgcSeasonOrder.updated,
    bool ascending = false,
    bool? finished,
    String? area,
    String? year,
    int? styleId,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listBilibiliPgcSeasons(
    type: type,
    page: page,
    pageSize: pageSize,
    order: order,
    ascending: ascending,
    finished: finished,
    area: area,
    year: year,
    styleId: styleId,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<BilibiliPgcTimelineInfo> listBilibiliPgcTimeline({
    required BilibiliPgcTimelineKind type,
    int beforeDays = 3,
    int afterDays = 7,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listBilibiliPgcTimeline(
    type: type,
    beforeDays: beforeDays,
    afterDays: afterDays,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<BilibiliPlaylistListPage> listBilibiliPlaylist(
    BilibiliPlaylistListIntent intent, {
    int page = 1,
    int pageSize = 30,
    String? cursor,
    String search = '',
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listBilibiliPlaylist(
    intent,
    page: page,
    pageSize: pageSize,
    cursor: cursor,
    search: search,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<CloudreveListPage> listCloudrevePage(
    String path, {
    String? keyword,
    int page = 1,
    int max = 20,
    int? offset,
    String? cursor,
    String serverId = '',
    String instanceName = '',
  }) => SyncTvService.listCloudrevePage(
    path,
    keyword: keyword,
    page: page,
    max: max,
    offset: offset,
    cursor: cursor,
    serverId: serverId,
    instanceName: instanceName,
  );

  @override
  Future<douyin.ListUserPostsResponse> listDouyinUserPosts(
    String secUid, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listDouyinUserPosts(
    secUid,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<EmbyListPage> listEmbyPage(
    EmbyListMode mode, {
    String targetId = '',
    List<String> itemTypes = const [],
    String? keyword,
    int page = 1,
    int max = 20,
    String serverId = '',
    String instanceName = '',
  }) => SyncTvService.listEmbyPage(
    mode,
    targetId: targetId,
    itemTypes: itemTypes,
    keyword: keyword,
    page: page,
    max: max,
    serverId: serverId,
    instanceName: instanceName,
  );

  @override
  Future<FnosFileListPage> listFnosFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listFnosFiles(
    serverId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<FnosMediaListPage> listFnosMediaItems(
    String serverId, {
    FnosMediaCollection collection = FnosMediaCollection.library,
    String libraryGuid = '',
    String parentGuid = '',
    int page = 1,
    int pageSize = 50,
    List<String> mediaTypes = const [],
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listFnosMediaItems(
    serverId,
    collection: collection,
    libraryGuid: libraryGuid,
    parentGuid: parentGuid,
    page: page,
    pageSize: pageSize,
    mediaTypes: mediaTypes,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<List<FnosMediaLibraryInfo>> listFnosMediaLibraries(
    String serverId, {
    String instanceName = '',
  }) => SyncTvService.listFnosMediaLibraries(
    serverId,
    instanceName: instanceName,
  );

  @override
  Future<RoomMediaLibraryPage> listMediaLibrary(
    String roomId, {
    int? page,
    String? cursor,
    int pageSize = 50,
    String playlistId = '',
    String? target,
    String search = '',
    source_enum.SourceProvider sourceProvider =
        source_enum.SourceProvider.SOURCE_PROVIDER_UNSPECIFIED,
    Map<String, dynamic>? previewSourceConfig,
    source_config.PlaylistSourceConfig? typedPreviewSourceConfig,
    String providerInstanceName = '',
    client_enum.MediaListSortBy sortBy =
        client_enum.MediaListSortBy.MEDIA_LIST_SORT_BY_POSITION,
    client_enum.SortDirection sortDirection =
        client_enum.SortDirection.SORT_DIRECTION_ASC,
    client_enum.ResourceAvailabilityFilter availability =
        client_enum.ResourceAvailabilityFilter.RESOURCE_AVAILABILITY_FILTER_ALL,
    bool refresh = false,
  }) => SyncTvService.listMediaLibrary(
    roomId,
    page: page,
    cursor: cursor,
    pageSize: pageSize,
    playlistId: playlistId,
    target: target,
    search: search,
    sourceProvider: sourceProvider,
    previewSourceConfig: previewSourceConfig,
    typedPreviewSourceConfig: typedPreviewSourceConfig,
    providerInstanceName: providerInstanceName,
    sortBy: sortBy,
    sortDirection: sortDirection,
    availability: availability,
    refresh: refresh,
  );

  @override
  Future<NextcloudFileListPage> listNextcloudFavorites(
    String serverId, {
    int page = 1,
    int pageSize = 50,
    String instanceName = '',
  }) => SyncTvService.listNextcloudFavorites(
    serverId,
    page: page,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<NextcloudFileListPage> listNextcloudFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listNextcloudFiles(
    serverId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<QnapFileListPage> listQnapFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listQnapFiles(
    serverId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<SeafileFileListPage> listSeafileFiles(
    String serverId,
    String repositoryId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listSeafileFiles(
    serverId,
    repositoryId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<SeafileFileListPage> listSeafileRepositories(
    String serverId, {
    int page = 1,
    int pageSize = 50,
    String instanceName = '',
  }) => SyncTvService.listSeafileRepositories(
    serverId,
    page: page,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<SeafileFileListPage> listSeafileStarred(
    String serverId, {
    int page = 1,
    int pageSize = 50,
    String instanceName = '',
  }) => SyncTvService.listSeafileStarred(
    serverId,
    page: page,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<SynologyFileListPage> listSynologyFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listSynologyFiles(
    serverId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<List<SynologyVideoLibraryInfo>> listSynologyLibraries(
    String serverId, {
    String instanceName = '',
  }) =>
      SyncTvService.listSynologyLibraries(serverId, instanceName: instanceName);

  @override
  Future<SynologyVideoListPage> listSynologyVideos(
    String serverId, {
    required SynologyVideoCollection collection,
    required int libraryId,
    int? tvShowId,
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listSynologyVideos(
    serverId,
    collection: collection,
    libraryId: libraryId,
    tvShowId: tvShowId,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<tiktok.ListUserPostsResponse> listTikTokUserPosts(
    String secUid, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listTikTokUserPosts(
    secUid,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<TrueNasFileListPage> listTrueNasFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listTrueNasFiles(
    serverId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<twitch.ListCategoryStreamsResponse> listTwitchCategoryStreams({
    required String categoryId,
    required String categoryName,
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listTwitchCategoryStreams(
    categoryId: categoryId,
    categoryName: categoryName,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<twitch.ListChannelItemsResponse> listTwitchChannelItems(
    String resource, {
    required source_enum.TwitchPlaylistContent content,
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listTwitchChannelItems(
    resource,
    content: content,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<twitch.ListFollowedLiveResponse> listTwitchFollowedLive({
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listTwitchFollowedLive(
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<twitch.ListScheduleResponse> listTwitchSchedule(
    String broadcasterId, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listTwitchSchedule(
    broadcasterId,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<twitch.ListTopCategoriesResponse> listTwitchTopCategories({
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.listTwitchTopCategories(
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<youtube.ListResponse> listYoutube(youtube.ListRequest request) =>
      SyncTvService.listYoutube(request);

  @override
  Future<AlistLoginInfo> loginAList(
    String host,
    String username,
    String hashedPassword, {
    String otpCode = '',
    String otpSecret = '',
    String instanceName = '',
  }) => SyncTvService.loginAList(
    host,
    username,
    hashedPassword,
    otpCode: otpCode,
    otpSecret: otpSecret,
    instanceName: instanceName,
  );

  @override
  Future<void> loginBilibiliSms({
    required String sessionToken,
    required String code,
  }) => SyncTvService.loginBilibiliSms(sessionToken: sessionToken, code: code);

  @override
  Future<String> loginCloudreve(
    String host,
    String email,
    String password, {
    String instanceName = '',
  }) => SyncTvService.loginCloudreve(
    host,
    email,
    password,
    instanceName: instanceName,
  );

  @override
  Future<EmbyLoginInfo> loginEmbyInfo(
    String host,
    String username,
    String password, {
    String apiKey = '',
    bool passwordless = false,
    String instanceName = '',
  }) => SyncTvService.loginEmbyInfo(
    host,
    username,
    password,
    apiKey: apiKey,
    passwordless: passwordless,
    instanceName: instanceName,
  );

  @override
  Future<FnosLoginInfo> loginFnos({
    required String endpoint,
    required String username,
    required String password,
    String webdavEndpoint = '',
    String mediaEndpoint = '',
    String twoFactorCode = '',
    bool trustDevice = true,
    String instanceName = '',
  }) => SyncTvService.loginFnos(
    endpoint: endpoint,
    username: username,
    password: password,
    webdavEndpoint: webdavEndpoint,
    mediaEndpoint: mediaEndpoint,
    twoFactorCode: twoFactorCode,
    trustDevice: trustDevice,
    instanceName: instanceName,
  );

  @override
  Future<NextcloudBindInfo> loginNextcloud({
    required String endpoint,
    required String username,
    required String appPassword,
    String instanceName = '',
  }) => SyncTvService.loginNextcloud(
    endpoint: endpoint,
    username: username,
    appPassword: appPassword,
    instanceName: instanceName,
  );

  @override
  Future<QnapBindInfo> loginQnap({
    required String endpoint,
    required String username,
    required String password,
    String instanceName = '',
  }) => SyncTvService.loginQnap(
    endpoint: endpoint,
    username: username,
    password: password,
    instanceName: instanceName,
  );

  @override
  Future<SeafileBindInfo> loginSeafile({
    required String endpoint,
    required String username,
    required String password,
    String instanceName = '',
  }) => SyncTvService.loginSeafile(
    endpoint: endpoint,
    username: username,
    password: password,
    instanceName: instanceName,
  );

  @override
  Future<SynologyBindInfo> loginSynology({
    required String endpoint,
    required String username,
    required String password,
    String otpCode = '',
    String deviceName = '',
    String instanceName = '',
  }) => SyncTvService.loginSynology(
    endpoint: endpoint,
    username: username,
    password: password,
    otpCode: otpCode,
    deviceName: deviceName,
    instanceName: instanceName,
  );

  @override
  Future<TrueNasBindInfo> loginTrueNas({
    required String endpoint,
    required String apiKey,
    String instanceName = '',
  }) => SyncTvService.loginTrueNas(
    endpoint: endpoint,
    apiKey: apiKey,
    instanceName: instanceName,
  );

  @override
  Future<void> logoutAList(String serverId) =>
      SyncTvService.logoutAList(serverId);

  @override
  Future<void> logoutBilibili() => SyncTvService.logoutBilibili();

  @override
  Future<void> logoutCloudreve(String serverId) =>
      SyncTvService.logoutCloudreve(serverId);

  @override
  Future<void> logoutEmby(String serverId) =>
      SyncTvService.logoutEmby(serverId);

  @override
  Future<void> logoutFnos(String serverId) =>
      SyncTvService.logoutFnos(serverId);

  @override
  Future<void> logoutNextcloud(String serverId) =>
      SyncTvService.logoutNextcloud(serverId);

  @override
  Future<void> logoutQnap(String serverId) =>
      SyncTvService.logoutQnap(serverId);

  @override
  Future<void> logoutSeafile(String serverId) =>
      SyncTvService.logoutSeafile(serverId);

  @override
  Future<void> logoutSynology(String serverId) =>
      SyncTvService.logoutSynology(serverId);

  @override
  Future<void> logoutTrueNas(String serverId) =>
      SyncTvService.logoutTrueNas(serverId);

  @override
  Future<BilibiliParseInfo> parseBilibiliInfo(
    String url, {
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.parseBilibiliInfo(
    url,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<NextcloudBindInfo> pollNextcloudLoginFlow({
    required String endpoint,
    required NextcloudLoginFlowInfo flow,
    String instanceName = '',
  }) => SyncTvService.pollNextcloudLoginFlow(
    endpoint: endpoint,
    flow: flow,
    instanceName: instanceName,
  );

  @override
  Future<provider_common.PreparedMediaSource> prepareDirectUrl(
    provider_common.PrepareDirectUrlRequest intent,
  ) => SyncTvService.prepareDirectUrl(intent);

  @override
  Future<provider_common.PreparedMediaSource> prepareLiveProxy(
    provider_common.PrepareLiveProxyRequest intent,
  ) => SyncTvService.prepareLiveProxy(intent);

  @override
  Future<provider_common.PreparedMediaSource> prepareRtmp(
    source_enum.RtmpStreamMode mode,
  ) => SyncTvService.prepareRtmp(mode);

  @override
  Future<acfun.ResolveResponse> resolveAcFun(
    String resource, {
    String instanceName = '',
  }) => SyncTvService.resolveAcFun(resource, instanceName: instanceName);

  @override
  Future<cctv.ResolveResponse> resolveCctv(
    String resource, {
    String instanceName = '',
  }) => SyncTvService.resolveCctv(resource, instanceName: instanceName);

  @override
  Future<douyin.ResolveResponse> resolveDouyin(
    String resource, {
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.resolveDouyin(
    resource,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<douyu.ResolveResponse> resolveDouyu(
    String resource, {
    String instanceName = '',
  }) => SyncTvService.resolveDouyu(resource, instanceName: instanceName);

  @override
  Future<huya.ResolveResponse> resolveHuya(
    String resource, {
    String instanceName = '',
  }) => SyncTvService.resolveHuya(resource, instanceName: instanceName);

  @override
  Future<provider_common.PlaybackProxyPolicy> resolvePlaybackProxyPolicy(
    provider_common.DiscoveredSource source,
  ) => SyncTvService.resolvePlaybackProxyPolicy(source);

  @override
  Future<tiktok.ResolveResponse> resolveTikTok(
    String resource, {
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.resolveTikTok(
    resource,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<twitch.ResolveResponse> resolveTwitch(
    String resource, {
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.resolveTwitch(
    resource,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<youtube.ResolveResponse> resolveYoutube(
    String resource, {
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.resolveYoutube(
    resource,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<twitch.SearchLiveChannelsResponse> searchTwitchLiveChannels(
    String query, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  }) => SyncTvService.searchTwitchLiveChannels(
    query,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
    shared: shared,
  );

  @override
  Future<BilibiliSmsLoginInfo> sendBilibiliSms({
    required BilibiliSmsLoginInfo session,
    required String phone,
    required String validate,
  }) => SyncTvService.sendBilibiliSms(
    session: session,
    phone: phone,
    validate: validate,
  );

  @override
  Future<bool> setFnosFavorite(
    String serverId,
    String itemGuid,
    bool favorite, {
    String instanceName = '',
  }) => SyncTvService.setFnosFavorite(
    serverId,
    itemGuid,
    favorite,
    instanceName: instanceName,
  );

  @override
  Future<bool> setFnosWatched(
    String serverId,
    String itemGuid,
    bool watched, {
    String instanceName = '',
  }) => SyncTvService.setFnosWatched(
    serverId,
    itemGuid,
    watched,
    instanceName: instanceName,
  );

  @override
  Future<BilibiliQrLoginInfo> startBilibiliQrLogin({
    String instanceName = '',
  }) => SyncTvService.startBilibiliQrLogin(instanceName: instanceName);

  @override
  Future<BilibiliSmsLoginInfo> startBilibiliSmsLogin({
    String instanceName = '',
  }) => SyncTvService.startBilibiliSmsLogin(instanceName: instanceName);

  @override
  Future<NextcloudLoginFlowInfo> startNextcloudLoginFlow(String endpoint) =>
      SyncTvService.startNextcloudLoginFlow(endpoint);

  @override
  Future<void> unbindDouyin(String serverId) =>
      SyncTvService.unbindDouyin(serverId);

  @override
  Future<void> unbindTikTok(String serverId) =>
      SyncTvService.unbindTikTok(serverId);

  @override
  Future<void> unbindTwitch(String serverId) =>
      SyncTvService.unbindTwitch(serverId);

  @override
  Future<void> unbindYoutube(String serverId) =>
      SyncTvService.unbindYoutube(serverId);

  @override
  Future<void> unlockSeafileLibrary(
    String serverId,
    String repositoryId,
    String password, {
    String instanceName = '',
  }) => SyncTvService.unlockSeafileLibrary(
    serverId,
    repositoryId,
    password,
    instanceName: instanceName,
  );
}
