// Generated by tool/generate_feature_gateways.dart.
import 'package:synctv_app/features/providers/application/provider_gateway.dart';
import 'package:synctv_app/data/synctv_api/synctv_service.dart';
import 'package:synctv_app/contracts/synctv_api_types.dart';
import 'package:synctv_app/src/generated/proto/providers/acfun.pb.dart'
    as acfun;
import 'package:synctv_app/src/generated/proto/providers/bilibili.pbenum.dart'
    as bilibili_enum;
import 'package:synctv_app/src/generated/proto/providers/cctv.pb.dart' as cctv;
import 'package:synctv_app/src/generated/proto/client.pbenum.dart'
    as client_enum;
import 'package:synctv_app/src/generated/proto/providers/douyin.pb.dart'
    as douyin;
import 'package:synctv_app/src/generated/proto/providers/douyu.pb.dart'
    as douyu;
import 'package:synctv_app/src/generated/proto/providers/huya.pb.dart' as huya;
import 'package:synctv_app/src/generated/proto/source_config.pb.dart'
    as source_config;
import 'package:synctv_app/src/generated/proto/source_config.pbenum.dart'
    as source_enum;
import 'package:synctv_app/src/generated/proto/providers/tiktok.pb.dart'
    as tiktok;
import 'package:synctv_app/src/generated/proto/providers/twitch.pb.dart'
    as twitch;
import 'package:synctv_app/src/generated/proto/providers/youtube.pb.dart'
    as youtube;

final class SyncTvProviderGateway implements ProviderGateway {
  const SyncTvProviderGateway();

  @override
  Future<String> addAcFunMedia(
    String roomId, {
    String playlistId = '',
    required String kind,
    required String id,
    String? episodeQuery,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addAcFunMedia(
    roomId,
    playlistId: playlistId,
    kind: kind,
    id: id,
    episodeQuery: episodeQuery,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addAlistMedia(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String path,
    String password = '',
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addAlistMedia(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    path: path,
    password: password,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addCctvMedia(
    String roomId, {
    String playlistId = '',
    required String resource,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addCctvMedia(
    roomId,
    playlistId: playlistId,
    resource: resource,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addCloudreveMedia(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String path,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addCloudreveMedia(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    path: path,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addDirectUrlMedia(
    String roomId, {
    String playlistId = '',
    required String url,
    required source_enum.PlaybackKind playbackKind,
    Map<String, String> headers = const {},
    String name = '',
    bool preferProxy = false,
    bool proxyOnly = false,
  }) => SyncTvService.addDirectUrlMedia(
    roomId,
    playlistId: playlistId,
    url: url,
    playbackKind: playbackKind,
    headers: headers,
    name: name,
    preferProxy: preferProxy,
    proxyOnly: proxyOnly,
  );

  @override
  Future<String> addDouyuMedia(
    String roomId, {
    String playlistId = '',
    required String room,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addDouyuMedia(
    roomId,
    playlistId: playlistId,
    room: room,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addEmbyMedia(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String itemId,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addEmbyMedia(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    itemId: itemId,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addFnosFileMedia(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String path,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addFnosFileMedia(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    path: path,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addFnosMediaLibraryItem(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String itemGuid,
    String mediaGuid = '',
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addFnosMediaLibraryItem(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    itemGuid: itemGuid,
    mediaGuid: mediaGuid,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addHuyaMedia(
    String roomId, {
    String playlistId = '',
    required String kind,
    required String id,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addHuyaMedia(
    roomId,
    playlistId: playlistId,
    kind: kind,
    id: id,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addLiveProxyMedia(
    String roomId, {
    String playlistId = '',
    required source_config.LiveProxyMediaSourceConfig sourceConfig,
    String name = '',
  }) => SyncTvService.addLiveProxyMedia(
    roomId,
    playlistId: playlistId,
    sourceConfig: sourceConfig,
    name: name,
  );

  @override
  Future<void> addMediaBatch(String roomId, List<Map<String, dynamic>> items) =>
      SyncTvService.addMediaBatch(roomId, items);

  @override
  Future<String> addMediaFromSourceConfig(
    String roomId, {
    String playlistId = '',
    String providerInstanceName = '',
    required source_config.MediaSourceConfig sourceConfig,
    String name = '',
  }) => SyncTvService.addMediaFromSourceConfig(
    roomId,
    playlistId: playlistId,
    providerInstanceName: providerInstanceName,
    sourceConfig: sourceConfig,
    name: name,
  );

  @override
  Future<String> addNextcloudMedia(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String path,
    required int fileId,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addNextcloudMedia(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    path: path,
    fileId: fileId,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addQnapMedia(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String path,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addQnapMedia(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    path: path,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addRtmpMedia(
    String roomId, {
    String playlistId = '',
    String name = '',
    source_enum.RtmpStreamMode mode =
        source_enum.RtmpStreamMode.RTMP_STREAM_MODE_DEFAULT,
  }) => SyncTvService.addRtmpMedia(
    roomId,
    playlistId: playlistId,
    name: name,
    mode: mode,
  );

  @override
  Future<String> addSeafileMedia(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String repositoryId,
    required String path,
    required String objectId,
    required bool hasThumbnail,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addSeafileMedia(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    repositoryId: repositoryId,
    path: path,
    objectId: objectId,
    hasThumbnail: hasThumbnail,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addSynologyFileMedia(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String path,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addSynologyFileMedia(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    path: path,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addSynologyLibraryMedia(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String kind,
    required int itemId,
    required int fileId,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addSynologyLibraryMedia(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    kind: kind,
    itemId: itemId,
    fileId: fileId,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<String> addTrueNasMedia(
    String roomId, {
    String playlistId = '',
    required String serverId,
    required String path,
    String name = '',
    String providerInstanceName = '',
  }) => SyncTvService.addTrueNasMedia(
    roomId,
    playlistId: playlistId,
    serverId: serverId,
    path: path,
    name: name,
    providerInstanceName: providerInstanceName,
  );

  @override
  Future<DouyinBindInfo> bindDouyin({
    required String label,
    required String cookie,
    String instanceName = '',
  }) => SyncTvService.bindDouyin(
    label: label,
    cookie: cookie,
    instanceName: instanceName,
  );

  @override
  Future<TikTokBindInfo> bindTikTok({
    required String label,
    required String cookie,
    String instanceName = '',
  }) => SyncTvService.bindTikTok(
    label: label,
    cookie: cookie,
    instanceName: instanceName,
  );

  @override
  Future<TwitchBindInfo> bindTwitch({
    required String authToken,
    String deviceId = '',
    String clientIntegrity = '',
    String instanceName = '',
  }) => SyncTvService.bindTwitch(
    authToken: authToken,
    deviceId: deviceId,
    clientIntegrity: clientIntegrity,
    instanceName: instanceName,
  );

  @override
  Future<YoutubeBindInfo> bindYoutube({
    required String label,
    String visitorData = '',
    String poToken = '',
    String cookie = '',
    String instanceName = '',
  }) => SyncTvService.bindYoutube(
    label: label,
    visitorData: visitorData,
    poToken: poToken,
    cookie: cookie,
    instanceName: instanceName,
  );

  @override
  Future<bilibili_enum.QRLoginStatus> checkBilibiliQrLogin(
    String key, {
    String instanceName = '',
  }) => SyncTvService.checkBilibiliQrLogin(key, instanceName: instanceName);

  @override
  Future<RoomPlaylistItem> createPlaylist(
    String roomId, {
    required String name,
    String parentId = '',
    String sourceProvider = '',
    Map<String, dynamic> sourceConfig = const {},
    String providerInstanceName = '',
    String description = '',
  }) => SyncTvService.createPlaylist(
    roomId,
    name: name,
    parentId: parentId,
    sourceProvider: sourceProvider,
    sourceConfig: sourceConfig,
    providerInstanceName: providerInstanceName,
    description: description,
  );

  @override
  Future<RoomPlaylistItem> createPlaylistFromSourceConfig(
    String roomId, {
    required String name,
    required source_config.PlaylistSourceConfig sourceConfig,
    String parentId = '',
    String providerInstanceName = '',
    String description = '',
  }) => SyncTvService.createPlaylistFromSourceConfig(
    roomId,
    name: name,
    sourceConfig: sourceConfig,
    parentId: parentId,
    providerInstanceName: providerInstanceName,
    description: description,
  );

  @override
  Future<RtmpPublishKeyInfo> createRtmpPublishKeyInfo(
    String roomId,
    String mediaId,
  ) => SyncTvService.createRtmpPublishKeyInfo(roomId, mediaId);

  @override
  Future<AlistAccountInfo> getAlistAccount(
    String serverId, {
    String instanceName = '',
  }) => SyncTvService.getAlistAccount(serverId, instanceName: instanceName);

  @override
  Future<List<AlistBindInfo>> getAllAlistBindInfos() =>
      SyncTvService.getAllAlistBindInfos();

  @override
  Future<List<BilibiliBindInfo>> getAllBilibiliBindInfos() =>
      SyncTvService.getAllBilibiliBindInfos();

  @override
  Future<List<CloudreveBindInfo>> getAllCloudreveBindInfos() =>
      SyncTvService.getAllCloudreveBindInfos();

  @override
  Future<List<DouyinBindInfo>> getAllDouyinBindInfos() =>
      SyncTvService.getAllDouyinBindInfos();

  @override
  Future<List<EmbyBindInfo>> getAllEmbyBindInfos() =>
      SyncTvService.getAllEmbyBindInfos();

  @override
  Future<List<FnosBindInfo>> getAllFnosBindInfos() =>
      SyncTvService.getAllFnosBindInfos();

  @override
  Future<List<NextcloudBindInfo>> getAllNextcloudBindInfos() =>
      SyncTvService.getAllNextcloudBindInfos();

  @override
  Future<List<QnapBindInfo>> getAllQnapBindInfos() =>
      SyncTvService.getAllQnapBindInfos();

  @override
  Future<List<SeafileBindInfo>> getAllSeafileBindInfos() =>
      SyncTvService.getAllSeafileBindInfos();

  @override
  Future<List<SynologyBindInfo>> getAllSynologyBindInfos() =>
      SyncTvService.getAllSynologyBindInfos();

  @override
  Future<List<TikTokBindInfo>> getAllTikTokBindInfos() =>
      SyncTvService.getAllTikTokBindInfos();

  @override
  Future<List<TrueNasBindInfo>> getAllTrueNasBindInfos() =>
      SyncTvService.getAllTrueNasBindInfos();

  @override
  Future<List<TwitchBindInfo>> getAllTwitchBindInfos() =>
      SyncTvService.getAllTwitchBindInfos();

  @override
  Future<List<YoutubeBindInfo>> getAllYoutubeBindInfos() =>
      SyncTvService.getAllYoutubeBindInfos();

  @override
  Future<BilibiliAccountInfo> getBilibiliAccount({String instanceName = ''}) =>
      SyncTvService.getBilibiliAccount(instanceName: instanceName);

  @override
  Future<CloudreveAccountInfo> getCloudreveAccount(
    String serverId, {
    String instanceName = '',
  }) => SyncTvService.getCloudreveAccount(serverId, instanceName: instanceName);

  @override
  Future<EmbyAccountInfo> getEmbyAccount(
    String serverId, {
    String instanceName = '',
  }) => SyncTvService.getEmbyAccount(serverId, instanceName: instanceName);

  @override
  Future<PublicSettingsInfo> getPublicSettings({bool refresh = false}) =>
      SyncTvService.getPublicSettings(refresh: refresh);

  @override
  Future<QnapCapabilitiesInfo> getQnapCapabilities(
    String serverId, {
    String instanceName = '',
  }) => SyncTvService.getQnapCapabilities(serverId, instanceName: instanceName);

  @override
  Future<RoomStreamEntryInfo> getRtmpStreamInfo({
    required String roomId,
    required String mediaId,
  }) => SyncTvService.getRtmpStreamInfo(roomId: roomId, mediaId: mediaId);

  @override
  Future<tiktok.GetUserResponse> getTikTokUser(
    String uniqueId, {
    String instanceName = '',
  }) => SyncTvService.getTikTokUser(uniqueId, instanceName: instanceName);

  @override
  Future<AlistListPage> listAlistPage(
    String path, {
    String? keyword,
    int page = 1,
    int max = 20,
    String password = '',
    String serverId = '',
    String instanceName = '',
  }) => SyncTvService.listAlistPage(
    path,
    keyword: keyword,
    page: page,
    max: max,
    password: password,
    serverId: serverId,
    instanceName: instanceName,
  );

  @override
  Future<List<String>> listAvailableProviderInstances({
    String providerType = '',
  }) =>
      SyncTvService.listAvailableProviderInstances(providerType: providerType);

  @override
  Future<List<BilibiliFavoriteFolderInfo>> listBilibiliFavoriteFolders({
    String instanceName = '',
  }) => SyncTvService.listBilibiliFavoriteFolders(instanceName: instanceName);

  @override
  Future<BilibiliFollowedPgcPage> listBilibiliFollowedPgc({
    required bool cinema,
    int page = 1,
    int pageSize = 30,
    String instanceName = '',
  }) => SyncTvService.listBilibiliFollowedPgc(
    cinema: cinema,
    page: page,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<List<BilibiliLiveAreaInfo>> listBilibiliLiveAreas({
    String instanceName = '',
  }) => SyncTvService.listBilibiliLiveAreas(instanceName: instanceName);

  @override
  Future<BilibiliPgcSeasonPage> listBilibiliPgcSeasons({
    required BilibiliPgcSeasonKind type,
    int page = 1,
    int pageSize = 30,
    BilibiliPgcSeasonOrder order = BilibiliPgcSeasonOrder.updated,
    bool ascending = false,
    bool? finished,
    String? area,
    String? year,
    int? styleId,
    String instanceName = '',
  }) => SyncTvService.listBilibiliPgcSeasons(
    type: type,
    page: page,
    pageSize: pageSize,
    order: order,
    ascending: ascending,
    finished: finished,
    area: area,
    year: year,
    styleId: styleId,
    instanceName: instanceName,
  );

  @override
  Future<BilibiliPgcTimelineInfo> listBilibiliPgcTimeline({
    required BilibiliPgcTimelineKind type,
    int beforeDays = 3,
    int afterDays = 7,
    String instanceName = '',
  }) => SyncTvService.listBilibiliPgcTimeline(
    type: type,
    beforeDays: beforeDays,
    afterDays: afterDays,
    instanceName: instanceName,
  );

  @override
  Future<CloudreveListPage> listCloudrevePage(
    String path, {
    String? keyword,
    int page = 1,
    int max = 20,
    int? offset,
    String? cursor,
    String serverId = '',
    String instanceName = '',
  }) => SyncTvService.listCloudrevePage(
    path,
    keyword: keyword,
    page: page,
    max: max,
    offset: offset,
    cursor: cursor,
    serverId: serverId,
    instanceName: instanceName,
  );

  @override
  Future<douyin.ListUserPostsResponse> listDouyinUserPosts(
    String secUid, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
  }) => SyncTvService.listDouyinUserPosts(
    secUid,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<EmbyListPage> listEmbyPage(
    String path, {
    String? keyword,
    int page = 1,
    int max = 20,
    String serverId = '',
    String instanceName = '',
  }) => SyncTvService.listEmbyPage(
    path,
    keyword: keyword,
    page: page,
    max: max,
    serverId: serverId,
    instanceName: instanceName,
  );

  @override
  Future<FnosFileListPage> listFnosFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listFnosFiles(
    serverId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<FnosMediaListPage> listFnosMediaItems(
    String serverId, {
    FnosMediaCollection collection = FnosMediaCollection.library,
    String ancestorGuid = '',
    int page = 1,
    int pageSize = 50,
    List<String> mediaTypes = const ['Movie', 'TV', 'Directory', 'Video'],
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listFnosMediaItems(
    serverId,
    collection: collection,
    ancestorGuid: ancestorGuid,
    page: page,
    pageSize: pageSize,
    mediaTypes: mediaTypes,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<List<FnosMediaLibraryInfo>> listFnosMediaLibraries(
    String serverId, {
    String instanceName = '',
  }) => SyncTvService.listFnosMediaLibraries(
    serverId,
    instanceName: instanceName,
  );

  @override
  Future<RoomMediaLibraryPage> listMediaLibrary(
    String roomId, {
    int page = 1,
    String? cursor,
    int pageSize = 50,
    String playlistId = '',
    String? target,
    String search = '',
    String sourceProvider = '',
    Map<String, dynamic>? previewSourceConfig,
    source_config.PlaylistSourceConfig? typedPreviewSourceConfig,
    String providerInstanceName = '',
    client_enum.MediaListSortBy sortBy =
        client_enum.MediaListSortBy.MEDIA_LIST_SORT_BY_POSITION,
    client_enum.SortDirection sortDirection =
        client_enum.SortDirection.SORT_DIRECTION_ASC,
    client_enum.ResourceAvailabilityFilter availability =
        client_enum.ResourceAvailabilityFilter.RESOURCE_AVAILABILITY_FILTER_ALL,
    bool refresh = false,
  }) => SyncTvService.listMediaLibrary(
    roomId,
    page: page,
    cursor: cursor,
    pageSize: pageSize,
    playlistId: playlistId,
    target: target,
    search: search,
    sourceProvider: sourceProvider,
    previewSourceConfig: previewSourceConfig,
    typedPreviewSourceConfig: typedPreviewSourceConfig,
    providerInstanceName: providerInstanceName,
    sortBy: sortBy,
    sortDirection: sortDirection,
    availability: availability,
    refresh: refresh,
  );

  @override
  Future<NextcloudFileListPage> listNextcloudFavorites(
    String serverId, {
    int page = 1,
    int pageSize = 50,
    String instanceName = '',
  }) => SyncTvService.listNextcloudFavorites(
    serverId,
    page: page,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<NextcloudFileListPage> listNextcloudFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listNextcloudFiles(
    serverId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<QnapFileListPage> listQnapFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listQnapFiles(
    serverId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<SeafileFileListPage> listSeafileFiles(
    String serverId,
    String repositoryId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listSeafileFiles(
    serverId,
    repositoryId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<SeafileFileListPage> listSeafileRepositories(
    String serverId, {
    int page = 1,
    int pageSize = 50,
    String instanceName = '',
  }) => SyncTvService.listSeafileRepositories(
    serverId,
    page: page,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<SeafileFileListPage> listSeafileStarred(
    String serverId, {
    int page = 1,
    int pageSize = 50,
    String instanceName = '',
  }) => SyncTvService.listSeafileStarred(
    serverId,
    page: page,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<SynologyFileListPage> listSynologyFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listSynologyFiles(
    serverId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<List<SynologyVideoLibraryInfo>> listSynologyLibraries(
    String serverId, {
    String instanceName = '',
  }) =>
      SyncTvService.listSynologyLibraries(serverId, instanceName: instanceName);

  @override
  Future<SynologyVideoListPage> listSynologyVideos(
    String serverId, {
    required SynologyVideoCollection collection,
    required int libraryId,
    int? tvShowId,
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listSynologyVideos(
    serverId,
    collection: collection,
    libraryId: libraryId,
    tvShowId: tvShowId,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<tiktok.ListUserPostsResponse> listTikTokUserPosts(
    String secUid, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
  }) => SyncTvService.listTikTokUserPosts(
    secUid,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<TrueNasFileListPage> listTrueNasFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  }) => SyncTvService.listTrueNasFiles(
    serverId,
    path,
    page: page,
    pageSize: pageSize,
    search: search,
    instanceName: instanceName,
  );

  @override
  Future<twitch.ListCategoryStreamsResponse> listTwitchCategoryStreams({
    required String categoryId,
    required String categoryName,
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
  }) => SyncTvService.listTwitchCategoryStreams(
    categoryId: categoryId,
    categoryName: categoryName,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<twitch.ListChannelItemsResponse> listTwitchChannelItems(
    String channel, {
    required source_enum.TwitchPlaylistContent content,
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
  }) => SyncTvService.listTwitchChannelItems(
    channel,
    content: content,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<twitch.ListFollowedLiveResponse> listTwitchFollowedLive({
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
  }) => SyncTvService.listTwitchFollowedLive(
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<twitch.ListScheduleResponse> listTwitchSchedule(
    String broadcasterId, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
  }) => SyncTvService.listTwitchSchedule(
    broadcasterId,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<twitch.ListTopCategoriesResponse> listTwitchTopCategories({
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
  }) => SyncTvService.listTwitchTopCategories(
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<AlistLoginInfo> loginAList(
    String host,
    String username,
    String hashedPassword, {
    String otpCode = '',
    String otpSecret = '',
    String instanceName = '',
  }) => SyncTvService.loginAList(
    host,
    username,
    hashedPassword,
    otpCode: otpCode,
    otpSecret: otpSecret,
    instanceName: instanceName,
  );

  @override
  Future<void> loginBilibiliSms({
    required String sessionToken,
    required String code,
  }) => SyncTvService.loginBilibiliSms(sessionToken: sessionToken, code: code);

  @override
  Future<String> loginCloudreve(
    String host,
    String email,
    String password, {
    String instanceName = '',
  }) => SyncTvService.loginCloudreve(
    host,
    email,
    password,
    instanceName: instanceName,
  );

  @override
  Future<EmbyLoginInfo> loginEmbyInfo(
    String host,
    String username,
    String password, {
    String apiKey = '',
    String instanceName = '',
  }) => SyncTvService.loginEmbyInfo(
    host,
    username,
    password,
    apiKey: apiKey,
    instanceName: instanceName,
  );

  @override
  Future<FnosLoginInfo> loginFnos({
    required String endpoint,
    required String username,
    required String password,
    String webdavEndpoint = '',
    String mediaEndpoint = '',
    String twoFactorCode = '',
    bool trustDevice = true,
    String instanceName = '',
  }) => SyncTvService.loginFnos(
    endpoint: endpoint,
    username: username,
    password: password,
    webdavEndpoint: webdavEndpoint,
    mediaEndpoint: mediaEndpoint,
    twoFactorCode: twoFactorCode,
    trustDevice: trustDevice,
    instanceName: instanceName,
  );

  @override
  Future<NextcloudBindInfo> loginNextcloud({
    required String endpoint,
    required String username,
    required String appPassword,
    String instanceName = '',
  }) => SyncTvService.loginNextcloud(
    endpoint: endpoint,
    username: username,
    appPassword: appPassword,
    instanceName: instanceName,
  );

  @override
  Future<QnapBindInfo> loginQnap({
    required String endpoint,
    required String username,
    required String password,
    String instanceName = '',
  }) => SyncTvService.loginQnap(
    endpoint: endpoint,
    username: username,
    password: password,
    instanceName: instanceName,
  );

  @override
  Future<SeafileBindInfo> loginSeafile({
    required String endpoint,
    required String username,
    required String password,
    String instanceName = '',
  }) => SyncTvService.loginSeafile(
    endpoint: endpoint,
    username: username,
    password: password,
    instanceName: instanceName,
  );

  @override
  Future<SynologyBindInfo> loginSynology({
    required String endpoint,
    required String username,
    required String password,
    String otpCode = '',
    String deviceName = '',
    String instanceName = '',
  }) => SyncTvService.loginSynology(
    endpoint: endpoint,
    username: username,
    password: password,
    otpCode: otpCode,
    deviceName: deviceName,
    instanceName: instanceName,
  );

  @override
  Future<TrueNasBindInfo> loginTrueNas({
    required String endpoint,
    required String apiKey,
    String instanceName = '',
  }) => SyncTvService.loginTrueNas(
    endpoint: endpoint,
    apiKey: apiKey,
    instanceName: instanceName,
  );

  @override
  Future<void> logoutAList(String serverId) =>
      SyncTvService.logoutAList(serverId);

  @override
  Future<void> logoutBilibili() => SyncTvService.logoutBilibili();

  @override
  Future<void> logoutCloudreve(String serverId) =>
      SyncTvService.logoutCloudreve(serverId);

  @override
  Future<void> logoutEmby(String serverId) =>
      SyncTvService.logoutEmby(serverId);

  @override
  Future<void> logoutFnos(String serverId) =>
      SyncTvService.logoutFnos(serverId);

  @override
  Future<void> logoutNextcloud(String serverId) =>
      SyncTvService.logoutNextcloud(serverId);

  @override
  Future<void> logoutQnap(String serverId) =>
      SyncTvService.logoutQnap(serverId);

  @override
  Future<void> logoutSeafile(String serverId) =>
      SyncTvService.logoutSeafile(serverId);

  @override
  Future<void> logoutSynology(String serverId) =>
      SyncTvService.logoutSynology(serverId);

  @override
  Future<void> logoutTrueNas(String serverId) =>
      SyncTvService.logoutTrueNas(serverId);

  @override
  Future<BilibiliParseInfo> parseBilibiliInfo(
    String url, {
    String instanceName = '',
  }) => SyncTvService.parseBilibiliInfo(url, instanceName: instanceName);

  @override
  Future<NextcloudBindInfo> pollNextcloudLoginFlow({
    required String endpoint,
    required NextcloudLoginFlowInfo flow,
    String instanceName = '',
  }) => SyncTvService.pollNextcloudLoginFlow(
    endpoint: endpoint,
    flow: flow,
    instanceName: instanceName,
  );

  @override
  Future<acfun.ResolveResponse> resolveAcFun(String resource) =>
      SyncTvService.resolveAcFun(resource);

  @override
  Future<cctv.ResolveResponse> resolveCctv(String resource) =>
      SyncTvService.resolveCctv(resource);

  @override
  Future<douyin.ResolveResponse> resolveDouyin(
    String resource, {
    String instanceName = '',
  }) => SyncTvService.resolveDouyin(resource, instanceName: instanceName);

  @override
  Future<douyu.ResolveResponse> resolveDouyu(String resource) =>
      SyncTvService.resolveDouyu(resource);

  @override
  Future<huya.ResolveResponse> resolveHuya(String resource) =>
      SyncTvService.resolveHuya(resource);

  @override
  Future<tiktok.ResolveResponse> resolveTikTok(
    String resource, {
    String instanceName = '',
  }) => SyncTvService.resolveTikTok(resource, instanceName: instanceName);

  @override
  Future<twitch.ResolveResponse> resolveTwitch(
    String resource, {
    String instanceName = '',
  }) => SyncTvService.resolveTwitch(resource, instanceName: instanceName);

  @override
  Future<youtube.ResolveResponse> resolveYoutube(
    String resource, {
    String instanceName = '',
  }) => SyncTvService.resolveYoutube(resource, instanceName: instanceName);

  @override
  Future<twitch.SearchLiveChannelsResponse> searchTwitchLiveChannels(
    String query, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
  }) => SyncTvService.searchTwitchLiveChannels(
    query,
    cursor: cursor,
    pageSize: pageSize,
    instanceName: instanceName,
  );

  @override
  Future<BilibiliSmsLoginInfo> sendBilibiliSms({
    required BilibiliSmsLoginInfo session,
    required String phone,
    required String validate,
  }) => SyncTvService.sendBilibiliSms(
    session: session,
    phone: phone,
    validate: validate,
  );

  @override
  Future<bool> setFnosFavorite(
    String serverId,
    String itemGuid,
    bool favorite, {
    String instanceName = '',
  }) => SyncTvService.setFnosFavorite(
    serverId,
    itemGuid,
    favorite,
    instanceName: instanceName,
  );

  @override
  Future<bool> setFnosWatched(
    String serverId,
    String itemGuid,
    bool watched, {
    String instanceName = '',
  }) => SyncTvService.setFnosWatched(
    serverId,
    itemGuid,
    watched,
    instanceName: instanceName,
  );

  @override
  Future<BilibiliQrLoginInfo> startBilibiliQrLogin({
    String instanceName = '',
  }) => SyncTvService.startBilibiliQrLogin(instanceName: instanceName);

  @override
  Future<BilibiliSmsLoginInfo> startBilibiliSmsLogin({
    String instanceName = '',
  }) => SyncTvService.startBilibiliSmsLogin(instanceName: instanceName);

  @override
  Future<NextcloudLoginFlowInfo> startNextcloudLoginFlow(String endpoint) =>
      SyncTvService.startNextcloudLoginFlow(endpoint);

  @override
  Future<void> unbindDouyin(String serverId) =>
      SyncTvService.unbindDouyin(serverId);

  @override
  Future<void> unbindTikTok(String serverId) =>
      SyncTvService.unbindTikTok(serverId);

  @override
  Future<void> unbindTwitch(String serverId) =>
      SyncTvService.unbindTwitch(serverId);

  @override
  Future<void> unbindYoutube(String serverId) =>
      SyncTvService.unbindYoutube(serverId);

  @override
  Future<void> unlockSeafileLibrary(
    String serverId,
    String repositoryId,
    String password, {
    String instanceName = '',
  }) => SyncTvService.unlockSeafileLibrary(
    serverId,
    repositoryId,
    password,
    instanceName: instanceName,
  );
}
