// Generated by tool/generate_feature_gateways.dart.
import 'package:synctv_app/contracts/synctv_api_types.dart';
import 'package:synctv_app/src/generated/proto/providers/acfun.pb.dart'
    as acfun;
import 'package:synctv_app/src/generated/proto/providers/bilibili.pbenum.dart'
    as bilibili_enum;
import 'package:synctv_app/src/generated/proto/providers/cctv.pb.dart' as cctv;
import 'package:synctv_app/src/generated/proto/client.pb.dart' as client;
import 'package:synctv_app/src/generated/proto/client.pbenum.dart'
    as client_enum;
import 'package:synctv_app/src/generated/proto/providers/douyin.pb.dart'
    as douyin;
import 'package:synctv_app/src/generated/proto/providers/douyu.pb.dart'
    as douyu;
import 'package:synctv_app/src/generated/proto/providers/huya.pb.dart' as huya;
import 'package:synctv_app/src/generated/proto/providers/common.pb.dart'
    as provider_common;
import 'package:synctv_app/src/generated/proto/source_config.pb.dart'
    as source_config;
import 'package:synctv_app/src/generated/proto/source_config.pbenum.dart'
    as source_enum;
import 'package:synctv_app/src/generated/proto/providers/tiktok.pb.dart'
    as tiktok;
import 'package:synctv_app/src/generated/proto/providers/twitch.pb.dart'
    as twitch;
import 'package:synctv_app/src/generated/proto/providers/youtube.pb.dart'
    as youtube;

abstract interface class ProviderGateway {
  Future<String> addDiscoveredSource(
    String roomId, {
    required provider_common.DiscoveredSource source,
    String playlistId = '',
    String name = '',
  });

  Future<DouyinBindInfo> bindDouyin({
    required String label,
    required String cookie,
    String instanceName = '',
  });

  Future<TikTokBindInfo> bindTikTok({
    required String label,
    required String cookie,
    String instanceName = '',
  });

  Future<TwitchBindInfo> bindTwitch({
    required String authToken,
    String deviceId = '',
    String clientIntegrity = '',
    String instanceName = '',
  });

  Future<YoutubeBindInfo> bindYoutube({
    required String label,
    String visitorData = '',
    String poToken = '',
    String cookie = '',
    String instanceName = '',
  });

  Future<bilibili_enum.QRLoginStatus> checkBilibiliQrLogin(
    String key, {
    String instanceName = '',
  });

  Future<RtmpPublishKeyInfo> createRtmpPublishKeyInfo(
    String roomId,
    String mediaId, {
    required client.PublishKeyType keyType,
    int? expiresAt,
  });

  Future<AlistAccountInfo> getAlistAccount(
    String serverId, {
    String instanceName = '',
  });

  Future<List<AlistBindInfo>> getAllAlistBindInfos();

  Future<List<BilibiliBindInfo>> getAllBilibiliBindInfos();

  Future<List<CloudreveBindInfo>> getAllCloudreveBindInfos();

  Future<List<DouyinBindInfo>> getAllDouyinBindInfos();

  Future<List<EmbyBindInfo>> getAllEmbyBindInfos();

  Future<List<FnosBindInfo>> getAllFnosBindInfos();

  Future<List<NextcloudBindInfo>> getAllNextcloudBindInfos();

  Future<List<QnapBindInfo>> getAllQnapBindInfos();

  Future<List<SeafileBindInfo>> getAllSeafileBindInfos();

  Future<List<SynologyBindInfo>> getAllSynologyBindInfos();

  Future<List<TikTokBindInfo>> getAllTikTokBindInfos();

  Future<List<TrueNasBindInfo>> getAllTrueNasBindInfos();

  Future<List<TwitchBindInfo>> getAllTwitchBindInfos();

  Future<List<YoutubeBindInfo>> getAllYoutubeBindInfos();

  Future<BilibiliAccountInfo> getBilibiliAccount({String instanceName = ''});

  Future<CloudreveAccountInfo> getCloudreveAccount(
    String serverId, {
    String instanceName = '',
  });

  Future<EmbyAccountInfo> getEmbyAccount(
    String serverId, {
    String instanceName = '',
  });

  Future<PublicSettingsInfo> getPublicSettings({bool refresh = false});

  Future<QnapCapabilitiesInfo> getQnapCapabilities(
    String serverId, {
    String instanceName = '',
  });

  Future<RoomStreamEntryInfo> getRtmpStreamInfo({
    required String roomId,
    required String mediaId,
  });

  Future<tiktok.GetUserResponse> getTikTokUser(
    String resource, {
    String instanceName = '',
    bool shared = false,
  });

  Future<AlistListPage> listAlistPage(
    String path, {
    String? keyword,
    int page = 1,
    int max = 20,
    String password = '',
    String serverId = '',
    String instanceName = '',
  });

  Future<List<String>> listAvailableProviderInstances({
    String providerType = '',
  });

  Future<List<BilibiliFavoriteFolderInfo>> listBilibiliFavoriteFolders({
    String instanceName = '',
    bool shared = false,
  });

  Future<BilibiliFollowedPgcPage> listBilibiliFollowedPgc({
    required bool cinema,
    int page = 1,
    int pageSize = 30,
    String instanceName = '',
    bool shared = false,
  });

  Future<List<BilibiliLiveAreaInfo>> listBilibiliLiveAreas({
    String instanceName = '',
    bool shared = false,
  });

  Future<BilibiliPgcSeasonPage> listBilibiliPgcSeasons({
    required BilibiliPgcSeasonKind type,
    int page = 1,
    int pageSize = 30,
    BilibiliPgcSeasonOrder order = BilibiliPgcSeasonOrder.updated,
    bool ascending = false,
    bool? finished,
    String? area,
    String? year,
    int? styleId,
    String instanceName = '',
    bool shared = false,
  });

  Future<BilibiliPgcTimelineInfo> listBilibiliPgcTimeline({
    required BilibiliPgcTimelineKind type,
    int beforeDays = 3,
    int afterDays = 7,
    String instanceName = '',
    bool shared = false,
  });

  Future<BilibiliPlaylistListPage> listBilibiliPlaylist(
    BilibiliPlaylistListIntent intent, {
    int page = 1,
    int pageSize = 30,
    String? cursor,
    String search = '',
    String instanceName = '',
    bool shared = false,
  });

  Future<CloudreveListPage> listCloudrevePage(
    String path, {
    String? keyword,
    int page = 1,
    int max = 20,
    int? offset,
    String? cursor,
    String serverId = '',
    String instanceName = '',
  });

  Future<douyin.ListUserPostsResponse> listDouyinUserPosts(
    String secUid, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  });

  Future<EmbyListPage> listEmbyPage(
    EmbyListMode mode, {
    String targetId = '',
    List<String> itemTypes = const [],
    String? keyword,
    int page = 1,
    int max = 20,
    String serverId = '',
    String instanceName = '',
  });

  Future<FnosFileListPage> listFnosFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  });

  Future<FnosMediaListPage> listFnosMediaItems(
    String serverId, {
    FnosMediaCollection collection = FnosMediaCollection.library,
    String libraryGuid = '',
    String parentGuid = '',
    int page = 1,
    int pageSize = 50,
    List<String> mediaTypes = const [],
    String search = '',
    String instanceName = '',
  });

  Future<List<FnosMediaLibraryInfo>> listFnosMediaLibraries(
    String serverId, {
    String instanceName = '',
  });

  Future<RoomMediaLibraryPage> listMediaLibrary(
    String roomId, {
    int? page,
    String? cursor,
    int pageSize = 50,
    String playlistId = '',
    String? target,
    String search = '',
    source_enum.SourceProvider sourceProvider =
        source_enum.SourceProvider.SOURCE_PROVIDER_UNSPECIFIED,
    Map<String, dynamic>? previewSourceConfig,
    source_config.PlaylistSourceConfig? typedPreviewSourceConfig,
    String providerInstanceName = '',
    client_enum.MediaListSortBy sortBy =
        client_enum.MediaListSortBy.MEDIA_LIST_SORT_BY_POSITION,
    client_enum.SortDirection sortDirection =
        client_enum.SortDirection.SORT_DIRECTION_ASC,
    client_enum.ResourceAvailabilityFilter availability =
        client_enum.ResourceAvailabilityFilter.RESOURCE_AVAILABILITY_FILTER_ALL,
    bool refresh = false,
  });

  Future<NextcloudFileListPage> listNextcloudFavorites(
    String serverId, {
    int page = 1,
    int pageSize = 50,
    String instanceName = '',
  });

  Future<NextcloudFileListPage> listNextcloudFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  });

  Future<QnapFileListPage> listQnapFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  });

  Future<SeafileFileListPage> listSeafileFiles(
    String serverId,
    String repositoryId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  });

  Future<SeafileFileListPage> listSeafileRepositories(
    String serverId, {
    int page = 1,
    int pageSize = 50,
    String instanceName = '',
  });

  Future<SeafileFileListPage> listSeafileStarred(
    String serverId, {
    int page = 1,
    int pageSize = 50,
    String instanceName = '',
  });

  Future<SynologyFileListPage> listSynologyFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  });

  Future<List<SynologyVideoLibraryInfo>> listSynologyLibraries(
    String serverId, {
    String instanceName = '',
  });

  Future<SynologyVideoListPage> listSynologyVideos(
    String serverId, {
    required SynologyVideoCollection collection,
    required int libraryId,
    int? tvShowId,
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  });

  Future<tiktok.ListUserPostsResponse> listTikTokUserPosts(
    String secUid, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  });

  Future<TrueNasFileListPage> listTrueNasFiles(
    String serverId,
    String path, {
    int page = 1,
    int pageSize = 50,
    String search = '',
    String instanceName = '',
  });

  Future<twitch.ListCategoryStreamsResponse> listTwitchCategoryStreams({
    required String categoryId,
    required String categoryName,
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  });

  Future<twitch.ListChannelItemsResponse> listTwitchChannelItems(
    String resource, {
    required source_enum.TwitchPlaylistContent content,
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  });

  Future<twitch.ListFollowedLiveResponse> listTwitchFollowedLive({
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  });

  Future<twitch.ListScheduleResponse> listTwitchSchedule(
    String broadcasterId, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  });

  Future<twitch.ListTopCategoriesResponse> listTwitchTopCategories({
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  });

  Future<youtube.ListResponse> listYoutube(youtube.ListRequest request);

  Future<AlistLoginInfo> loginAList(
    String host,
    String username,
    String hashedPassword, {
    String otpCode = '',
    String otpSecret = '',
    String instanceName = '',
  });

  Future<void> loginBilibiliSms({
    required String sessionToken,
    required String code,
  });

  Future<String> loginCloudreve(
    String host,
    String email,
    String password, {
    String instanceName = '',
  });

  Future<EmbyLoginInfo> loginEmbyInfo(
    String host,
    String username,
    String password, {
    String apiKey = '',
    bool passwordless = false,
    String instanceName = '',
  });

  Future<FnosLoginInfo> loginFnos({
    required String endpoint,
    required String username,
    required String password,
    String webdavEndpoint = '',
    String mediaEndpoint = '',
    String twoFactorCode = '',
    bool trustDevice = true,
    String instanceName = '',
  });

  Future<NextcloudBindInfo> loginNextcloud({
    required String endpoint,
    required String username,
    required String appPassword,
    String instanceName = '',
  });

  Future<QnapBindInfo> loginQnap({
    required String endpoint,
    required String username,
    required String password,
    String instanceName = '',
  });

  Future<SeafileBindInfo> loginSeafile({
    required String endpoint,
    required String username,
    required String password,
    String instanceName = '',
  });

  Future<SynologyBindInfo> loginSynology({
    required String endpoint,
    required String username,
    required String password,
    String otpCode = '',
    String deviceName = '',
    String instanceName = '',
  });

  Future<TrueNasBindInfo> loginTrueNas({
    required String endpoint,
    required String apiKey,
    String instanceName = '',
  });

  Future<void> logoutAList(String serverId);

  Future<void> logoutBilibili();

  Future<void> logoutCloudreve(String serverId);

  Future<void> logoutEmby(String serverId);

  Future<void> logoutFnos(String serverId);

  Future<void> logoutNextcloud(String serverId);

  Future<void> logoutQnap(String serverId);

  Future<void> logoutSeafile(String serverId);

  Future<void> logoutSynology(String serverId);

  Future<void> logoutTrueNas(String serverId);

  Future<BilibiliParseInfo> parseBilibiliInfo(
    String url, {
    String instanceName = '',
    bool shared = false,
  });

  Future<NextcloudBindInfo> pollNextcloudLoginFlow({
    required String endpoint,
    required NextcloudLoginFlowInfo flow,
    String instanceName = '',
  });

  Future<provider_common.PreparedMediaSource> prepareDirectUrl(
    provider_common.PrepareDirectUrlRequest intent,
  );

  Future<provider_common.PreparedMediaSource> prepareLiveProxy(
    provider_common.PrepareLiveProxyRequest intent,
  );

  Future<provider_common.PreparedMediaSource> prepareRtmp(
    source_enum.RtmpStreamMode mode,
  );

  Future<acfun.ResolveResponse> resolveAcFun(
    String resource, {
    String instanceName = '',
  });

  Future<cctv.ResolveResponse> resolveCctv(
    String resource, {
    String instanceName = '',
  });

  Future<douyin.ResolveResponse> resolveDouyin(
    String resource, {
    String instanceName = '',
    bool shared = false,
  });

  Future<douyu.ResolveResponse> resolveDouyu(
    String resource, {
    String instanceName = '',
  });

  Future<huya.ResolveResponse> resolveHuya(
    String resource, {
    String instanceName = '',
  });

  Future<provider_common.PlaybackProxyPolicy> resolvePlaybackProxyPolicy(
    provider_common.DiscoveredSource source,
  );

  Future<tiktok.ResolveResponse> resolveTikTok(
    String resource, {
    String instanceName = '',
    bool shared = false,
  });

  Future<twitch.ResolveResponse> resolveTwitch(
    String resource, {
    String instanceName = '',
    bool shared = false,
  });

  Future<youtube.ResolveResponse> resolveYoutube(
    String resource, {
    String instanceName = '',
    bool shared = false,
  });

  Future<twitch.SearchLiveChannelsResponse> searchTwitchLiveChannels(
    String query, {
    String? cursor,
    int pageSize = 20,
    String instanceName = '',
    bool shared = false,
  });

  Future<BilibiliSmsLoginInfo> sendBilibiliSms({
    required BilibiliSmsLoginInfo session,
    required String phone,
    required String validate,
  });

  Future<bool> setFnosFavorite(
    String serverId,
    String itemGuid,
    bool favorite, {
    String instanceName = '',
  });

  Future<bool> setFnosWatched(
    String serverId,
    String itemGuid,
    bool watched, {
    String instanceName = '',
  });

  Future<BilibiliQrLoginInfo> startBilibiliQrLogin({String instanceName = ''});

  Future<BilibiliSmsLoginInfo> startBilibiliSmsLogin({
    String instanceName = '',
  });

  Future<NextcloudLoginFlowInfo> startNextcloudLoginFlow(String endpoint);

  Future<void> unbindDouyin(String serverId);

  Future<void> unbindTikTok(String serverId);

  Future<void> unbindTwitch(String serverId);

  Future<void> unbindYoutube(String serverId);

  Future<void> unlockSeafileLibrary(
    String serverId,
    String repositoryId,
    String password, {
    String instanceName = '',
  });
}
