// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum messagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Represents a relying party
///
/// Generated class from Pigeon that represents data sent in messages.
struct RelyingParty: Hashable, CustomStringConvertible {
  /// Name of the relying party
  var name: String
  /// ID of the relying party
  var id: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RelyingParty? {
    let name = pigeonVar_list[0] as! String
    let id = pigeonVar_list[1] as! String

    return RelyingParty(
      name: name,
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      id,
    ]
  }
  static func == (lhs: RelyingParty, rhs: RelyingParty) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.name, rhs.name) && messagesPigeonInternal.deepEquals(lhs.id, rhs.id)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RelyingParty")
    messagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
  }

  public var description: String {
    return "RelyingParty(name: \(String(describing: name)), id: \(String(describing: id)))"
  }
}

/// Represents a credential
///
/// Generated class from Pigeon that represents data sent in messages.
struct CredentialType: Hashable, CustomStringConvertible {
  /// The type of the credential.
  var type: String
  /// The ID of the credential.
  var id: String
  /// The transports of the credential.
  var transports: [String?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CredentialType? {
    let type = pigeonVar_list[0] as! String
    let id = pigeonVar_list[1] as! String
    let transports = pigeonVar_list[2] as! [String?]

    return CredentialType(
      type: type,
      id: id,
      transports: transports
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      id,
      transports,
    ]
  }
  static func == (lhs: CredentialType, rhs: CredentialType) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.type, rhs.type) && messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.transports, rhs.transports)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CredentialType")
    messagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: transports, hasher: &hasher)
  }

  public var description: String {
    return "CredentialType(type: \(String(describing: type)), id: \(String(describing: id)), transports: \(String(describing: transports)))"
  }
}

/// Represents a user
///
/// Generated class from Pigeon that represents data sent in messages.
struct User: Hashable, CustomStringConvertible {
  /// The name
  var name: String
  /// The ID
  var id: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> User? {
    let name = pigeonVar_list[0] as! String
    let id = pigeonVar_list[1] as! String

    return User(
      name: name,
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      id,
    ]
  }
  static func == (lhs: User, rhs: User) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.name, rhs.name) && messagesPigeonInternal.deepEquals(lhs.id, rhs.id)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("User")
    messagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
  }

  public var description: String {
    return "User(name: \(String(describing: name)), id: \(String(describing: id)))"
  }
}

/// Represents a register response
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegisterResponse: Hashable, CustomStringConvertible {
  /// The ID
  var id: String
  /// The raw ID
  var rawId: String
  /// The client data JSON
  var clientDataJSON: String
  /// The attestation object
  var attestationObject: String
  /// The supported transports for the authenticator
  var transports: [String?]
  /// The clientExtensionResults - PRF results
  var clientExtensionResults: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterResponse? {
    let id = pigeonVar_list[0] as! String
    let rawId = pigeonVar_list[1] as! String
    let clientDataJSON = pigeonVar_list[2] as! String
    let attestationObject = pigeonVar_list[3] as! String
    let transports = pigeonVar_list[4] as! [String?]
    let clientExtensionResults: [String?: Any?]? = nilOrValue(pigeonVar_list[5])

    return RegisterResponse(
      id: id,
      rawId: rawId,
      clientDataJSON: clientDataJSON,
      attestationObject: attestationObject,
      transports: transports,
      clientExtensionResults: clientExtensionResults
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      rawId,
      clientDataJSON,
      attestationObject,
      transports,
      clientExtensionResults,
    ]
  }
  static func == (lhs: RegisterResponse, rhs: RegisterResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.rawId, rhs.rawId) && messagesPigeonInternal.deepEquals(lhs.clientDataJSON, rhs.clientDataJSON) && messagesPigeonInternal.deepEquals(lhs.attestationObject, rhs.attestationObject) && messagesPigeonInternal.deepEquals(lhs.transports, rhs.transports) && messagesPigeonInternal.deepEquals(lhs.clientExtensionResults, rhs.clientExtensionResults)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterResponse")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: rawId, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: clientDataJSON, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: attestationObject, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: transports, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: clientExtensionResults, hasher: &hasher)
  }

  public var description: String {
    return "RegisterResponse(id: \(String(describing: id)), rawId: \(String(describing: rawId)), clientDataJSON: \(String(describing: clientDataJSON)), attestationObject: \(String(describing: attestationObject)), transports: \(String(describing: transports)), clientExtensionResults: \(String(describing: clientExtensionResults)))"
  }
}

/// Represents an authenticate response
///
/// Generated class from Pigeon that represents data sent in messages.
struct AuthenticateResponse: Hashable, CustomStringConvertible {
  /// The ID
  var id: String
  /// The raw ID
  var rawId: String
  /// The client data JSON
  var clientDataJSON: String
  /// The authenticator data
  var authenticatorData: String
  /// Signed challenge
  var signature: String
  var userHandle: String? = nil
  /// The clientExtensionResults - PRF results
  var clientExtensionResults: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthenticateResponse? {
    let id = pigeonVar_list[0] as! String
    let rawId = pigeonVar_list[1] as! String
    let clientDataJSON = pigeonVar_list[2] as! String
    let authenticatorData = pigeonVar_list[3] as! String
    let signature = pigeonVar_list[4] as! String
    let userHandle: String? = nilOrValue(pigeonVar_list[5])
    let clientExtensionResults: [String?: Any?]? = nilOrValue(pigeonVar_list[6])

    return AuthenticateResponse(
      id: id,
      rawId: rawId,
      clientDataJSON: clientDataJSON,
      authenticatorData: authenticatorData,
      signature: signature,
      userHandle: userHandle,
      clientExtensionResults: clientExtensionResults
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      rawId,
      clientDataJSON,
      authenticatorData,
      signature,
      userHandle,
      clientExtensionResults,
    ]
  }
  static func == (lhs: AuthenticateResponse, rhs: AuthenticateResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.rawId, rhs.rawId) && messagesPigeonInternal.deepEquals(lhs.clientDataJSON, rhs.clientDataJSON) && messagesPigeonInternal.deepEquals(lhs.authenticatorData, rhs.authenticatorData) && messagesPigeonInternal.deepEquals(lhs.signature, rhs.signature) && messagesPigeonInternal.deepEquals(lhs.userHandle, rhs.userHandle) && messagesPigeonInternal.deepEquals(lhs.clientExtensionResults, rhs.clientExtensionResults)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthenticateResponse")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: rawId, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: clientDataJSON, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: authenticatorData, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: signature, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: userHandle, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: clientExtensionResults, hasher: &hasher)
  }

  public var description: String {
    return "AuthenticateResponse(id: \(String(describing: id)), rawId: \(String(describing: rawId)), clientDataJSON: \(String(describing: clientDataJSON)), authenticatorData: \(String(describing: authenticatorData)), signature: \(String(describing: signature)), userHandle: \(String(describing: userHandle)), clientExtensionResults: \(String(describing: clientExtensionResults)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return RelyingParty.fromList(self.readValue() as! [Any?])
    case 130:
      return CredentialType.fromList(self.readValue() as! [Any?])
    case 131:
      return User.fromList(self.readValue() as! [Any?])
    case 132:
      return RegisterResponse.fromList(self.readValue() as! [Any?])
    case 133:
      return AuthenticateResponse.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RelyingParty {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CredentialType {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? User {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterResponse {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AuthenticateResponse {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PasskeysApi {
  func canAuthenticate() throws -> Bool
  func hasBiometrics() throws -> Bool
  func register(challenge: String, relyingParty: RelyingParty, user: User, excludeCredentials: [CredentialType], pubKeyCredValues: [Int64], canBePlatformAuthenticator: Bool, canBeSecurityKey: Bool, residentKeyPreference: String?, userVerificationPreference: String?, attestationPreference: String?, salt: String?, completion: @escaping (Result<RegisterResponse, Error>) -> Void)
  func authenticate(relyingPartyId: String, challenge: String, conditionalUI: Bool, allowedCredentials: [CredentialType], preferImmediatelyAvailableCredentials: Bool, userVerificationPreference: String?, salt: String?, completion: @escaping (Result<AuthenticateResponse, Error>) -> Void)
  func cancelCurrentAuthenticatorOperation(completion: @escaping (Result<Void, Error>) -> Void)
  func signalUnknownCredential(relyingPartyId: String, credentialId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func signalAllAcceptedCredentials(relyingPartyId: String, userId: String, allAcceptedCredentialIds: [String], completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PasskeysApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PasskeysApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PasskeysApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let canAuthenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.canAuthenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      canAuthenticateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.canAuthenticate()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      canAuthenticateChannel.setMessageHandler(nil)
    }
    let hasBiometricsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.hasBiometrics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasBiometricsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.hasBiometrics()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasBiometricsChannel.setMessageHandler(nil)
    }
    let registerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.register\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let challengeArg = args[0] as! String
        let relyingPartyArg = args[1] as! RelyingParty
        let userArg = args[2] as! User
        let excludeCredentialsArg = args[3] as! [CredentialType]
        let pubKeyCredValuesArg = args[4] as! [Int64]
        let canBePlatformAuthenticatorArg = args[5] as! Bool
        let canBeSecurityKeyArg = args[6] as! Bool
        let residentKeyPreferenceArg: String? = nilOrValue(args[7])
        let userVerificationPreferenceArg: String? = nilOrValue(args[8])
        let attestationPreferenceArg: String? = nilOrValue(args[9])
        let saltArg: String? = nilOrValue(args[10])
        api.register(challenge: challengeArg, relyingParty: relyingPartyArg, user: userArg, excludeCredentials: excludeCredentialsArg, pubKeyCredValues: pubKeyCredValuesArg, canBePlatformAuthenticator: canBePlatformAuthenticatorArg, canBeSecurityKey: canBeSecurityKeyArg, residentKeyPreference: residentKeyPreferenceArg, userVerificationPreference: userVerificationPreferenceArg, attestationPreference: attestationPreferenceArg, salt: saltArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerChannel.setMessageHandler(nil)
    }
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let relyingPartyIdArg = args[0] as! String
        let challengeArg = args[1] as! String
        let conditionalUIArg = args[2] as! Bool
        let allowedCredentialsArg = args[3] as! [CredentialType]
        let preferImmediatelyAvailableCredentialsArg = args[4] as! Bool
        let userVerificationPreferenceArg: String? = nilOrValue(args[5])
        let saltArg: String? = nilOrValue(args[6])
        api.authenticate(relyingPartyId: relyingPartyIdArg, challenge: challengeArg, conditionalUI: conditionalUIArg, allowedCredentials: allowedCredentialsArg, preferImmediatelyAvailableCredentials: preferImmediatelyAvailableCredentialsArg, userVerificationPreference: userVerificationPreferenceArg, salt: saltArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
    let cancelCurrentAuthenticatorOperationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.cancelCurrentAuthenticatorOperation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelCurrentAuthenticatorOperationChannel.setMessageHandler { _, reply in
        api.cancelCurrentAuthenticatorOperation { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelCurrentAuthenticatorOperationChannel.setMessageHandler(nil)
    }
    let signalUnknownCredentialChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.signalUnknownCredential\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signalUnknownCredentialChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let relyingPartyIdArg = args[0] as! String
        let credentialIdArg = args[1] as! String
        api.signalUnknownCredential(relyingPartyId: relyingPartyIdArg, credentialId: credentialIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signalUnknownCredentialChannel.setMessageHandler(nil)
    }
    let signalAllAcceptedCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.signalAllAcceptedCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signalAllAcceptedCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let relyingPartyIdArg = args[0] as! String
        let userIdArg = args[1] as! String
        let allAcceptedCredentialIdsArg = args[2] as! [String]
        api.signalAllAcceptedCredentials(relyingPartyId: relyingPartyIdArg, userId: userIdArg, allAcceptedCredentialIds: allAcceptedCredentialIdsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signalAllAcceptedCredentialsChannel.setMessageHandler(nil)
    }
  }
}
